### ISSUE TITLE
Compile broken due to snesmusic on Linux/Mac

### ISSUE THREAD

**Issue by BooBerry** [devinacker/bsnes-plus#104]
Tried this on Ubuntu, Arch Linux and macOS 10.12.2 and got this error when attempting to compile;

Assembler messages:
Fatal error: can't create obj/snesmusic.o: No such file or directory
make[1]: *** [Makefile:41: obj/snesmusic.o] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-michael/aur-bsnes-plus-git/src/bsnes-plus/snesmusic'
make: *** [Makefile:116: plugins] Error 2

**Comment by devinacker** [comment]
Sorry about that, I forgot to make sure the directory actually exists when cloning/updating. Should be fine now.
