### ISSUE TITLE
Feature request: RAM editor

### ISSUE THREAD

**Issue by GhbSmwc** [devinacker/bsnes-plus#105]
I notice that snes9x debugger ([link](https://www.smwcentral.net/?p=section&a=details&id=11501)) have the ability to manipulate the WRAM (0x7E0000 to 0x7FFFFF) can you add that to the memory editor?

**Comment by devinacker** [comment]
This feature already exists. Just point the memory editor to any address in the 0x7E0000-0x7FFFFF range.

**Comment by GhbSmwc** [comment]
sorry for late reply. Thanks, so the memory editor contains the entire memory map.
