### ISSUE TITLE
video filter Issues

### ISSUE THREAD

**Issue by yuya495** [devinacker/bsnes-plus#108]
I am using the latest bsnes-plus v 073 + 3 64 bit version
With the video filter Super Eagle
The operation of bsnes plus stops and the filter of Super Eagle can not be applied
Can I fix it?
![ws000002](https://cloud.githubusercontent.com/assets/8580180/23026254/fdb9514e-f4a3-11e6-81c1-a0ecec60368e.JPG)
![ws000001](https://cloud.githubusercontent.com/assets/8580180/23026255/00b003fc-f4a4-11e6-9128-7a4e5e15b896.JPG)

**Comment by yuya495** [comment]
My operating environment is
OS Windows7 professional 64bit
Memory 8 GB
CPU Inter (R) Core (TM) i 7-2600 3.40 GHz TB (3.80 GHz)
GPU NVIDIA GeForce GTX 580

**Comment by devinacker** [comment]
Do any of the other filters have the same problem?

**Comment by yuya495** [comment]
I am using Japanese translation because I am Japanese because I'm sorry for my English
No other filters work fine

**Comment by yuya495** [comment]
私は日本人で英語がへたですいませんグーグル 翻訳を使用しています
いいえ　他のフィルターは正常に動作します

**Comment by yuya495** [comment]
I'm Japanese and I'm sorry English is wrong, I use Google Translate
No other filters work fine

**Comment by yuya495** [comment]
I am using Japanese translation because I am Japanese because I'm sorry for my English
Other filters are working properly

**Comment by yuya495** [comment]
Because I am a Japanese, English is poor, and, I'm sorry, use English translation;, no, other filters are movement normally

**Comment by yuya495** [comment]
When Scanline abjust chose a filter of Super Eagle at the time of 100%, this did not stop it in 95% which were like the bug to stop movement of emulators
![ws000000](https://cloud.githubusercontent.com/assets/8580180/23038139/4930da3e-f4cc-11e6-8b21-363c5c433446.JPG)

**Comment by devinacker** [comment]
Which video driver are you using ("Configuration Settings" > "Advanced")?

If you switch to a different video driver and restart the emulator, does the problem still happen?

どのビデオドライバを使用していますか（「Configuration Settings」>「Advanced」）？

別のビデオドライバに切り替えてエミュレータを再起動すると、問題は解決されますか？

私もGoogle翻訳を使用しています。 うまくいけば、これは大丈夫です。

**Comment by yuya495** [comment]
ビデオドライバーは基本的にDirect3Dでプレイしています
他のビデオドライバーでもScanline abjust100%でSuper Eagleを使用すると
エミュレーターの動作が停止します
![ws000003](https://cloud.githubusercontent.com/assets/8580180/23079705/596ccd34-f591-11e6-8e5f-3bc8884cbe05.JPG)

Basically, the video driver is playing in Direct3D
Even with other video drivers using Super Eagle with Scanline abjust 100%
The operation of the emulator stops

**Comment by yuya495** [comment]
Scanline abjust 100% + Super Eagle = Emulator operation stopped
Scanline abjust 0% to 95% + Super Eagle = Emulator normal operation

**Comment by yuya495** [comment]
I shot a video
動画を撮影してみました
https://youtu.be/DgGNI4Vhda4

**Comment by devinacker** [comment]
私は動画がEmuCRによって提供される非公式のビルドを使用していることに気付きました。 最新の公式ビルドで問題はまだ発生していますか？(https://github.com/devinacker/bsnes-plus/releases/download/v073%2B3a/bsnes-plus-073.3a-x64.rar)

それ以外の場合は、おそらく非公式のビルドの問題です。 EmuCRによって提供されるビルドはテストされておらず、公式リリースビルドよりも安定性が低い可能性があります。

**Comment by yuya495** [comment]
I played successfully in the latest official build
Thanks devinacker
