### ISSUE TITLE
Feature request: Run to next VBlank/HBlank/NMI/IRQ

### ISSUE THREAD

**Issue by mrehkopf** [devinacker/bsnes-plus#117]
Hi, jwdonal brought this up at nesdev but at quick glance I didn't find a corresponding GitHub issue, so here it is ;)
Quoting jwdonal:

> 1) Would be totally outstanding if you could add buttons in the Debugger window for "Run to next Vblank" and "Run to next Hblank". That would be super powerful.

While I'm at it, being able to run up to the next triggering of NMI and IRQ would be quite helpful as well, e.g. when waiting for a "wait for ISR flag" loop to finish without having to set the breakpoints manually.

**Comment by jwdonal** [comment]
Another thing that would be a cherry on top is "Run to Line #N" where N can be set by the user.

I can't really help on the code (no clue how it works), but if you're not opposed to monetary incentives I'd be happy to make a $$ donation to the project (or a specific code contributor) to get this feature implemented. ;) This is not a bribe - I swear!!  XD
