### ISSUE TITLE
Joypad on Mac

### ISSUE THREAD

**Issue by sporchia** [devinacker/bsnes-plus#120]
Perhaps I'm missing something obvious, but how does one use a USB gamepad with this?

Mac OSX 10.12.4
bsnes-plus 073+3a
gamepad logitech dual action

**Comment by Optiroc** [comment]
Good question. I should dig up a USB-controller/adapter and see what happens.

**Comment by devinacker** [comment]
The Carbon input driver currently doesn't have joypad or mouse support, unfortunately.

I'm not too sure since I'm not a frequent Mac user, but it might be feasible to enable the SDL input driver as well, as long as SDL and Xlib are both available.

Otherwise, it might be a good idea to flesh out a proper Carbon or Cocoa input driver at some point.

**Comment by Optiroc** [comment]
I actually added mouse support in the Carbon driver semi-recently (only in my fork so far), so I might just as well look into joypad support as well.

**Comment by BooBerry** [comment]
@Optiroc I just tested a build of your latest commits with my Logitech Cordless RumblePad 2 and... nothing (tried buttons, not the axis). But that's okay, it's still early on! The gamepad does work on macOS and does work with an emulator I use in Wine, so it's not an incompatibility issue. Fortunately there are apps to map joystick to key presses - sadly I've not found a decent free app.

Higan also doesn't work with my gamepad, and honestly I don't ever expect it to either.

**Comment by Optiroc** [comment]
@BooBerry Could you try building the latest commit and launch bsnes+ from the command line. `../bsnes+.app/Contents/MacOS/bsnes` if you're in the bsnes dir in the repo.

I've added some more verbose logging of the macOS input driver. If at launch it logs the following
```
input_macos::ctor
input_macos::init
init_hid_manager: hid manager created
```
...we're sure that the driver inits properly. If you also get logs like these:
```
hid_register_device: 0x4ce98c80 - slot 0
```
...you've also connected a device that matches the HID joystick or gamepad profiles, and input events from it are funneled to the bsnes input driver. At that point it should also start logging all suitable events from said device.

 There's obviously many points where things may break as I've only tested with one USB gamepad so far. Can you find your device anywhere in the `About This Mac -> System Report...` listing? You could also run the "HID Dumper" ([source](https://developer.apple.com/library/content/samplecode/HID_Dumper/Introduction/Intro.html)) sample application from Apple, which dumps pretty extensive information about all connected HID devices.

**Comment by BooBerry** [comment]
Nope, nothing like that. Only thing in the verbose logging is a few `QWidget::paintEngine: Should no longer be called` and that's it. It's as I thought, it doesn't detect it at all.

And yes, the gamepad can be found in `System Report...`

![screen shot 2017-05-14 at 2 55 12 pm](https://cloud.githubusercontent.com/assets/5448916/26037270/7ab5b868-38b5-11e7-8f1a-69a617d083b2.png)

**Comment by Optiroc** [comment]
@BooBerry OK, that's promising at least... It seems the input driver doesn't init at all, which is unexpected but then there's good hope that your gamepad will work soon enough. In the bsnes preferences, can you make sure that `macOS` is selected as input driver? Then make sure that keyboard input works as usual. It probably doesn't if you don't see `input_macos::ctor` and `input_macos::init` logged.

If you can't get those items logged (in which case keyboard input surely won't work), try removing the configuration files in the `~/.bsnes` folder.

**Comment by BooBerry** [comment]
The driver was on macOS but I switched it to None, closed the app then reopened it and set it back to macOS. Success!

```
input_macos::ctor
input_macos::init
init_hid_manager: hid manager created
hid_register_device: 0x3959c270 - slot 0
```

**Comment by Optiroc** [comment]
@BooBerry Oh, that's cool! I probably shouldn't have changed name of the driver since this seemed to trip up something in the preferences deserialization at startup... Oh well.

Do you get anything else logged after that (specifically if you try pressing any and all buttons on your joypad)?

**Comment by BooBerry** [comment]
Yeah, I opened up SMW and the buttons work. I can't move, but I can sure jump and pause/unpause the game! 👍

**Comment by Optiroc** [comment]
@BooBerry Good to hear. From the `usage 0x0039` in your log it seems that the d-pad on your device is registering as a "hat switch". Which is kinda nice, since I don't have any device that uses hats here... I'll try getting in support for both axis and hats right away.

**Comment by Optiroc** [comment]
@BooBerry I've done some tinkering to handle the various possible input events that the devices I currently have available don't use. It's not completely unlikely that your gamepad works now, so please try it out when you got the time!

**Comment by BooBerry** [comment]
It fully works now. Both the d-pad and the analog sticks work now! Thanks a lot! 🥇

**Comment by Optiroc** [comment]
@BooBerry Great! I'm curious to hear what the d-pad and sticks register as in the input configuration (`JP0::Something`).

**Comment by BooBerry** [comment]
Here you go!

```
input.gamepad1.up = "JP0::Hat0.Up"
input.gamepad1.down = "JP0::Hat0.Down"
input.gamepad1.left = "JP0::Hat0.Left"
input.gamepad1.right = "JP0::Hat0.Right"
input.gamepad1.b = "JP0::Button6"
input.gamepad1.a = "JP0::Button7"
input.gamepad1.y = "JP0::Button5"
input.gamepad1.x = "JP0::Button8"
input.gamepad1.l = "JP0::Button9"
input.gamepad1.r = "JP0::Button10"
input.gamepad1.select = "JP0::Button13"
input.gamepad1.start = "JP0::Button14"
```

**Comment by Optiroc** [comment]
@BooBerry Nice, thanks. Do the analogue sticks register as something as well?

**Comment by BooBerry** [comment]
Yes they do.

```
input.gamepad1.up = "JP0::Axis1.Lo"
input.gamepad1.down = "JP0::Axis1.Hi"
input.gamepad1.left = "JP0::Axis0.Lo"
input.gamepad1.right = "JP0::Axis0.Hi"
```

**Comment by BooBerry** [comment]
The second analogue stick also registers nicely...

input.gamepad1.up = "JP0::Axis5.Lo"
input.gamepad1.down = "JP0::Axis5.Hi"
input.gamepad1.left = "JP0::Axis2.Lo"
input.gamepad1.right = "JP0::Axis2.Hi"

**Comment by devinacker** [comment]
Do you think this is ready for a PR yet?

**Comment by devinacker** [comment]
I guess this can probably be closed now that the PR has been merged and there is proper mouse and joypad support on macOS.
