### ISSUE TITLE
Color Math Emulation Bug

### ISSUE THREAD

**Issue by jwdonal** [devinacker/bsnes-plus#124]
I've tried this test ROM in several other emulators (no$sns, higan, snes9x, etc) and it looks correct. However, when running in bsnes-plus the fog/clouds are displayed with a different random color on each power-on/reset/load/reload. I'm running v073+3a.

[translucent.zip](https://github.com/devinacker/bsnes-plus/files/1044025/translucent.zip)

**Comment by jwdonal** [comment]
Another discovery. This issue only occurs with bsnes-accuracy.exe, it does _not_ happen with bsnes.exe.

**Comment by mrehkopf** [comment]
Seems to happen on purpose - the constant color register (writable via $2132) is probably random on bootup on a real PPU.
Palette color 0 is the background color for the Main Screen; the "Constant Color" can be considered the background color for the Sub Screen, e.g. the background color for BG3 when used as a pure Sub Screen layer for color math.
The attached test ROM doesn't initialize the constant color via $2132 (should write $E0 - upper 3 bits to select the color channels, 5 bits for the intensity value).

**Comment by devinacker** [comment]
Yeah, as others have mentioned, this is a result of recent versions randomizing some system state by default (even more so with the accuracy core) more or less the same way higan does it.

You can disable `snes.random` in your config file if you want, though it's not really recommended if you're trying to match the behavior of real hardware.
