### ISSUE TITLE
Problems compiling on *nix

### ISSUE THREAD

**Issue by DxRedJava** [devinacker/bsnes-plus#125]
There seems to be a **severe** lack of documentation regarding *nix operating systems. In light of this, I am getting the largest error I've ever seen and have no clue what it is or where to start searching. I am running Arch Linux x64 and have all the dependancies, but to no avail. Here is the error: [pastebin](https://pastebin.com/qSv53wV6)

**Comment by undisbeliever** [comment]
You need to tell the Makefile which version of moc/rcc to use.

Try:

    cd bsnes
    make moc=moc-qt4 rcc=rcc-qt4
