### ISSUE TITLE
Feature Request: Shortened traces for MVN/MVP

### ISSUE THREAD

**Issue by eduardomezencio** [devinacker/bsnes-plus#127]
I'm using the trace feature a lot to find some stuff, and it's very helpful, but sometimes there are some large data transfers with MVN and MVP and a single instruction ends up occupying thousands of lines in the output. This makes it hard to deal with trace files sometimes. Maybe there could be an option to omit these repetitions.

**Comment by devinacker** [comment]
To be fair, I think it'd be nice if mvn/mvp would only write one line to the log even when the trace mask is off, since it's basically just the CPU executing the same instruction repeatedly in a very predictable way. Unfortunately it'd be kind of messy to implement it that way.

**Comment by eduardomezencio** [comment]
So, what about leaving this issue open as a reminder? Maybe someone is or will be willing to pick it up..

**Comment by eduardomezencio** [comment]
I was checking the code now to see if I could be this person, I was thinking about just checking if the instruction is one of these and then turning on a flag that stops printing. This flag would be turned off when register A is FFFF. It would be something like this: (imagining the flag inBlockMove was defined and turned on when such instruction is executed)
```
if(!inBlockMove) {
    if(!traceMask || !(traceMaskCPU[addr >> 3] & (0x80 >> (addr & 7)))) {
        char text[256];
        SNES::cpu.disassemble_opcode(text, addr, config().debugger.showHClocks);
        tracefile.print(string() << text << "\n");
    }
}
else if(cpu.regs.a == 0xFFFF) // is this how you access registers?
    inBlockMove = false;
```
I haven't checked yet in your code how to get the current instruction, so I could write the code to turn on the flag, that's why this part is missing. 
(I found it quite strange that the code to print to the trace file is mixed up in the qt ui code, btw)

**Comment by Optiroc** [comment]
One caveat to consider is that block moves can be interrupted, and it's OK to start another block move within the interrupt and continue the other move when done.

**Comment by eduardomezencio** [comment]
Oh, I understand. Well, I don't seem to understand the inner workings of snes well enough to help with this, for now..

**Comment by undisbeliever** [comment]
I think a better algorithm would be something like:

    if registers.pc != lastPC and opcode != MVN and opcode != MVP:
        disassemble_opcode()
    lastPC = registers.pc
