### ISSUE TITLE
Feature request: Hide mouse pointer on fullscreen mode

### ISSUE THREAD

**Issue by PeladoFeo** [devinacker/bsnes-plus#132]
The mouse pointer is supposed to be hidden in fullscreen mode when the menu and status bars are, too.

**Comment by devinacker** [comment]
I can look into doing this soon, it shouldn't be too hard to manage.

In the meantime, as a cheap workaround, you could just move the cursor all the way down to temporarily hide it (on Windows, at least).

**Comment by MaxFireBR** [comment]
LOL :-) I liked the temporary solution thanks :-)
