### ISSUE TITLE
Data breakpoint comparison operator

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#133]
Currently, a read or write breakpoint with a value in the Data field will break if a read or write occurs containing that value.  It would be nice if you could select a comparison operator (==, !=, >, >=, <, <=) so that you could break, for example, on any nonzero write to address XXXX.  This is a pretty common feature in a lot of cheat search scanners, and it would be really useful in debugging, for similar reasons.

**Comment by devinacker** [comment]
Not a bad idea. I could try adding a small dropdown for selecting operators or something like that.

**Comment by qwertymodo** [comment]
Having brought up cheat search, I actually just realized that bsnes-plus already does exactly that in its cheat search dialog.

**Comment by devinacker** [comment]
This is available in the `newdebugger` WIP branch now, along with a general overhaul of the breakpoint editor that I may be adding other stuff to later.

**Comment by qwertymodo** [comment]
On the subject of debugger improvements, maybe I should create a separate issue ticket, but it would be nice to add DSP registers as a break source. Currently you can only do it indirectly by breaking on APU reads/writes to $F2/F3, using the "data" field to specify the destination register, but that only gets you breaks on *any* read/write to that register, you can't use the data field to break on specific values like you can to other destinations.
