### ISSUE TITLE
Manifest viewer

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#141]
Higan has a manifest viewer dialog to display the currently loaded manifest for the game you're playing, whether that's an actual manifest file or one generated in memory by icarus.  This is very useful when trying out various modifications to the default mapping for a game, for things like extending the ROM/SRAM size, adding a new expansion chip, etc.  Without that, it's rather tedious to generate those manifests.  It would be nice to have such a viewer in bsnes-plus since it still uses the old-style xml manifests.

**Comment by devinacker** [comment]
added in 40c795a6fb15109a95aa5b2932001d4705be6901
