### ISSUE TITLE
Mouse focus not returned after SNES mouse is disabled

### ISSUE THREAD

**Issue by CharlesCorrin** [devinacker/bsnes-plus#144]
Boot up a game that uses the SNES mouse. Say, Mario to Wario (Mario & Wario). Change the controller type to SNES mouse. Doesn't matter if it's port 1 or port 2, because it'll happen on both. Now try to switch back to gamepad or to anything else including the none option. The emulator will keep control of your mouse and won't let you have it back till you close the emulator completely.

Also, it would be good if there was a way to easily access the menus while the mouse cursor is trapped in the window. Maybe a button to toggle screen-trapping or something.

I'm using Windows 10 64-bit and the 64-bit version of the emulator.

**Comment by devinacker** [comment]
"Fixed" this by making the mouse automatically get released when changing inputs or powering off the SNES.

Additionally (including in existing builds) you can press Esc to manually release the mouse at any time.
