### ISSUE TITLE
.bin files

### ISSUE THREAD

**Issue by jjfmz42015** [devinacker/bsnes-plus#147]
How to I find out what .bin files I need for this build?

LIke I mean DSP1, C4??? 

Please let me know

**Comment by jjfmz42015** [comment]
anyone?

**Comment by devinacker** [comment]
You'll need these in the same directory as your ROMs:

* cx4.bin
* dsp1b.bin
* dsp2.bin
* dsp3.bin
* dsp4.bin
* st0010.bin
* st0011.bin

cx4.bin is only needed for the last official release. Recent dev builds and the next official release won't require it anymore.

**Comment by jjfmz42015** [comment]
what is the crc of the correct cx4.bin? and you are saying bsnes-plus-073.3a-x64 requires it?

**Comment by jjfmz42015** [comment]
is dsp1.bin not required? just 1b?
