### ISSUE TITLE
Allow viewing the sprite layer in the tilemap viewer

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#150]
It would be nice to be able to view the full sprite layer rather than only being able to view one sprite at a time in the sprite viewer.  The logical place for this would probably be to just put a "sprite" button next to the 4 BG buttons on the Tilemap Viewer for this purpose.

**Comment by devinacker** [comment]
Should this be considered supplanted by #202 (even though it's still separate from the tilemap viewer)?

**Comment by devinacker** [comment]
(similar) feature merged in #207
