### ISSUE TITLE
Captured screenshots are double width

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#151]
Any time I take a screenshot with the Capture Screenshot button, the picture is stretched horizontally to exactly double the width.  This seems like a simple fix, but it's rather annoying.

![alttp - vt_no-glitches-27_easy-open-ganon_0xvjnaxkvj-20171129-131745](https://user-images.githubusercontent.com/5988870/33399517-c1b5329a-d507-11e7-94fa-6efd180895cf.png)

**Comment by undisbeliever** [comment]
Looking into it it appears this bug occurs because the screenshot is saved after the video has been cropped and processed by the Video Filter.

Disabling the video filter will produce a screenshot with the original input size.

I'll have a look at the code and see if I can come up with something.

**Comment by devinacker** [comment]
This also happens in accuracy builds without a filter active due to the emulator always internally rendering 512px lines. 

I made a note about coming up with a way for filters not to affect screenshots a while back (#37) but never made time to really look into it.

**Comment by undisbeliever** [comment]
> This also happens in accuracy builds without a filter active due to the emulator always internally rendering 512px lines.

Upon closer inspection it appears that the screenshot was taken with the accuracy build and not the NTSC filter.

----

I've written some code (c848d68) that 
 * Bypasses the overscan, scanline filter and video filter settings when capturing screenshots.
 * Doubles height or width of the unfiltered screenshot as necessary (tested in both accuracy and comparability builds on 256x224, 512x224, 256x448 and 512x448 screen modes)

Unfiltered screenshots still honour the color adjustment settings.

When I figure out how to add configuration options I will make the unfiltered screenshots optional and create the appropriate pull request.

**Comment by devinacker** [comment]
Looks pretty good to me. If you're okay with me merging this, I can take care of making it a config option.

**Comment by undisbeliever** [comment]
I have no problem with you merging the code and making any necessary changes.

Between RL and the summer heat I've had no time to dig though the bsnes-plus source code and will appreciate you doing this for me.
