### ISSUE TITLE
Some missing info(s) in Tools -> Debugger -> Tools -> Properties viewer, also some request

### ISSUE THREAD

**Issue by GhbSmwc** [devinacker/bsnes-plus#152]
There is a [SNES DEV manuel](https://www.smwcentral.net/?p=section&a=details&id=13357) mentioning SA-1 registers $2250, $2221-$2252, $2253-$2254. According to the Manuel, it has signed multiplication, signed division (Signed/Unsigned=SignedQuotient, Unsigned Remainder), and "cumulative sum".  The multiply and divide takes 5 cycles for the calculation to complete. Multiplication result is $2306-$2309. Division result is ($2306-$2307) with the remainder at $2306-$2307. All numbers stored in any memory or registers are low endian.

Side note: Can you have an option to view any data table (like Tools -> Debugger -> S-PPU -> Sprite Viewer) in different radix values (decimal, hex, binary). That would be great. Thanks.

**Comment by devinacker** [comment]
Whoops, looks like I had a big "TODO" for SA-1 register values some time ago that I just never remembered to finish. I'll get on that sometime soon.

Adding support for different numerical bases to every debugger info view would probably be a little tedious, but I can think about doing that at some point.

**Comment by GhbSmwc** [comment]
sorry for the late reply, but thanks for replying. Another request: can you make the dropdown menu (from the menubar) that opens a new (sub)window bring the already-opened window to the front for all "window openers"? I've experienced where I did this:
Tools -> Debugger -> Tools -> Breakpoint editor. Try opening it twice, and the second time you try to do it, does nothing rather than bringing the already-opened breakpoint editor

Seems like you did it well with the memory editor, as trying to "re-open" it would bring the memory editor to the front
