### ISSUE TITLE
Fail to load save file for FIre Emblem: Genealogy of the Holy War patched with the Book of Holsety Translation Patch

### ISSUE THREAD

**Issue by Draco309** [devinacker/bsnes-plus#154]
BSNES Plus fails to load the save file for a patched version of Fire Emblem: Genealogy of the Holy War. It is only an issue with the Book of Holsety Translation Patch (found here: https://serenesforest.net/forums/index.php?/topic/63676-fe4-translation-patch-open-beta-v7/ ), as the untranslated and old translation both work and this issue does not occur with any other ROMs. The save file is still created, but appears to be blank even if the game has been saved. Any save states can be loaded. SNES9X does not have an issue loading save files with this ROM. It does not overwrite save files that were created from SNES9X, but also fails to load them. 

The save file created and ROM I am using are attached below in a ZIP file. 
[FE4.zip](https://github.com/devinacker/bsnes-plus/files/1565159/FE4.zip)

**Comment by devinacker** [comment]
I'll take a look at this when I'm home from work. My guess is that if the ROM is expanded it might be messing up the memory mapping heuristics somehow.

**Comment by devinacker** [comment]
Yep, checking it now and it looks like my suspicion was right. I recently mentioned in #155 that I need to fix some inaccurate memory mapping details that were fixed in higan fairly recently.

In the meantime, you can use a custom manifest to fix the issue, just put this in a file called `fe4.xml` in the same directory as the ROM (assuming your ROM is also called `fe4`:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<cartridge region='NTSC'>
  <rom>
    <map mode='shadow' address='00-3f:8000-ffff' offset='400000'/>
    <map mode='linear' address='40-7d:0000-ffff' offset='400000'/>
    <map mode='shadow' address='80-bf:8000-ffff' offset='000000'/>
    <map mode='linear' address='c0-ff:0000-ffff' offset='000000'/>
  </rom>
  <ram size='2000'>
    <map mode='linear' address='20-3f:6000-7fff'/>
    <map mode='linear' address='a0-bf:6000-7fff'/>
  </ram>
</cartridge>
```

**Comment by Draco309** [comment]
Thanks for the fix, and perfect timing too. I just finished the previous game I was playing through, nowI can return to this.

**Comment by devinacker** [comment]
fixed in an upcoming commit (testing a couple of other mapping changes still pending)
