### ISSUE TITLE
8BITDO gamepad in mode "controller" not work ?

### ISSUE THREAD

**Issue by Ludodmlk** [devinacker/bsnes-plus#156]
Hey ! 
I don't know if is normal but; when i use my 8BITDO in bluetooth mode "controller" (not in keybord mode)
i can't configure my input ! 
have you got a solution ? 😃

**Comment by devinacker** [comment]
Are you able to successfully use other types of controllers over bluetooth? (I don't have any to test with myself, sorry)

Also, what OS and input driver (settings > configuration > advanced) are you using? Does selecting a different input driver and restarting the emulator make any difference?

**Comment by devinacker** [comment]
closing due to lack of input, if you're still having the same issue with the most recent release then please reply with more information
