### ISSUE TITLE
Export to MIDI in Sound Viewer?

### ISSUE THREAD

**Issue by ireece1** [devinacker/bsnes-plus#163]
It would be a pretty interesting feature to be able to record the playing sounds into a MIDI file. I could see in being used to aid in ROM hacking

**Comment by devinacker** [comment]
I feel like this is a little bit out of scope for an emulator. The sound viewer is mainly intended as an easy way to visualize some of the state of the sound hardware.

There are already programs for converting SPC files to MIDI, IT, etc. that you may find useful.
