### ISSUE TITLE
MSU-1 on BS-X cartridges

### ISSUE THREAD

**Issue by Phillip-May** [devinacker/bsnes-plus#165]
Is it possible to do use custom ROM mapping on a BS-X cartridge to add MSU-1 support without having to patch the ROM to make it standalone like the BS Zelda translation did?

I am trying to add msu-1 mapping to a bs-x cartridge and whenever I try to load a cartridge using the BS-X bio and my game.xml it gives error 08 implying the memory mapping is messed up.

My current xml file for reference
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cartridge region="NTSC">
  <bsx>
    <mcu>
      <map address="00-3f:8000-ffff"/>
      <map address="80-bf:8000-ffff"/>
      <map address="40-7f:0000-ffff"/>
      <map address="c0-ff:0000-ffff"/>
      <map address="20-3f:6000-7fff"/>
    </mcu>
    <mmio>
      <map address="00-3f:5000-5fff"/>
      <map address="80-bf:5000-5fff"/>
    </mmio>
  </bsx>
  <rom>
    <map mode="linear" address="00-6f:8000-ffff"/>
    <map mode="linear" address="80-ff:8000-ffff"/>
  </rom>

  <ram size="2000">
    <map mode="linear" address="70:0000-2fff"/>
  </ram>

  <msu1>
    <map address="00-3f:2000-2007"/>
    <map address="80-bf:2000-2007"/>
    <mmio>
      <map address="00-3f:2000-2007"/>
      <map address="80-bf:2000-2007"/>
    </mmio>
  </msu1> 
</cartridge>
```

**Comment by devinacker** [comment]
This is what an automatically generated manifest for the BS-X base cartridge looks like:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<cartridge region='NTSC'>
  <rom>
    <map mode='linear' address='00-3f:8000-ffff'/>
    <map mode='linear' address='80-bf:8000-ffff'/>
  </rom>
  <ram size='8000'>
    <map mode='linear' address='10-17:5000-5fff'/>
  </ram>
  <bsx>
    <mcc>
      <map address='00-0f:5000-5fff'/>
    </mcc>
  </bsx>
</cartridge>
```

Adding the normal `msu1` element to the above _should_ work.

Keep in mind this manifest applies to the base cartridge, _not_ the memory pack containing the actual game (these have manifests too, but any memory mapping information in them is ignored).

**Comment by Phillip-May** [comment]
When you say the memory mapping info for the memory pack is ignored, does that mean it inherits from the BS-X BIOS or does it mean you cant change their memory mapping?
