### ISSUE TITLE
Bug in Cx4::nextpc()

### ISSUE THREAD

**Issue by KevinCathcart** [devinacker/bsnes-plus#172]
It looks like is a bug in cx4.cpp's `nextpc` function:
```c++
void Cx4::nextpc() {
  regs.pc++;
  if (regs.pc & 0xff == 0) {
    // continue to next page or stop
```

If my understanding is correct the if statement will never be executed. This is because
`==` has higher precedence than bitwise `&`, and therefore it is interpreted as `egs.pc & (0xff == 0)`, which simplifies to `regs.pc & false`, which in turn simplifies to `false`.

**Comment by devinacker** [comment]
Good catch, thanks.
