### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by GhbSmwc** [devinacker/bsnes-plus#173]
During my test on the disassembler part, I made this simple (and pointless to be used in a game) code to see how it display (I use uberasm tool for SMW as an easy test to see how the opcode gets displayed depending on the 8/16-bit mode for accumulator (A) and the indexes (X and Y)):

<pre>main:
	LDA #$00
	STA $00
	BRA skip
	
	db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	
	REP #$20
	LDA #$1234
	STA $00
	SEP #$20
	
	skip:
	LDX #$05
	loop:
	STZ $00
	DEX
	BPL loop
	
	REP #$20
	LDA #$0001
	STA $00
	SEP #$20
	LDA #$12
	STA $01
	rtl</pre>

When doing a breakpoint, the codes won't show (shows as "..." other than the ones whats the pc is currently on (colored green font) and before that (blue font)), but when hitting run to wait till this code to be executed again, I got this after a few steps:

<pre>909cc6 ldx #$05
909cc8 stz $00 ;>highlighted in green (current PC location)
909cca dex
909ccb bpl $9cc8
909ccd rep #$20
909ccf lda #$01 ;\uhh... A is 16-bit mode, it is supposed to display LDA #$0001
909cd2 sta $00  ;/
909cd4 sep #$20
909cd6 lda #$12 ;\appears as LDA #$8512 when 909ccf is executed (after A is set to 16-bit mode).
909cd8 sta $01  ;/
909cda rtl</pre>

When the PC counter goes to the glitch-displayed opcode/instruction (909ccf), it then updates to the correct opcode. I assume that bsnes plus cannot predict the opcode and thus assumes the code was like that.

Another annoyance I've found is that the shortcut key (F5 and F6 to run and step) does not apply on the disassembler window, only on the main debug window.

Feature request: on the readme, inform the user that when disassembling a RAM code, that the WHOLE thing updates (if you have a code in RAM, and it writes anywhere at an address the pc already executed (blue font), would change), and also include an option to disabled updated past-executed opcodes if the user doesn't want it to be changed (so only update stuff at or ahead of the pc current location (green font)). Here is my testing:

My code:
<pre>	LDX.b #$05             ;\Write 6 nops (each nop takes 1 byte)
	-                      ;|
	LDA #$EA               ;|
	STA $7F8000,x          ;|
	DEX                    ;|
	BPL -                  ;/
	
	LDA #$8F               ;\\STA $7F8000 (opcode byte)
	STA $7F8006            ;|/
	LDA #$00               ;|\Byte 0 (low byte)
	STA $7F8007            ;|/
	LDA #$80               ;|\Byte 1 (middle byte)
	STA $7F8008            ;|/
	LDA #$7F               ;|\Byte 2 (bank byte)
	STA $7F8009            ;//
	
	LDA #$6B               ;\RTL (random write)
	STA $7F800A            ;/
	
	JSL $7F8000
	
	- BRA -                ;>infinite loop to prevent messing up smw's oam.
	rtl
;
;7F8000 to 7F8005 : all nops
;7F8006 to 7F8009 : STZ $7F8000
;7F800A           : writes RTL at the beginning</pre>

Executed code (in disassembler):
<pre>7f8000 nop ;>after executing at 7f8006, this then turns into RTL. 
7f8001 nop
7f8002 nop
7f8003 nop
7f8004 nop
7f8005 nop
7f8006 sta $7f8000</pre>

**Comment by GhbSmwc** [comment]
Actually, I'm totally wrong, the disassembler display not only update codes at or later from the program counter address, it actually changes the opcodes before it as well when toggling between 8/16-bit mode, thus, this example:

<pre>	LDA #$00
	STA $00
	BRA skip
	
	db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	
	REP #$20
	LDA #$1234
	STA $00
	SEP #$20
	
	skip:
	LDX #$05
	loop:
	STZ $00
	DEX
	BPL loop
	
	REP #$20
	LDA #$0001
	STA $00
	SEP #$20
	LDA #$12
	STA $01
	REP #$20
	LDA #$0000
	STA $0F
	SEP #$20
	
	rtl</pre>

disassembler:
<pre>909ce9 ldx #$05
909ceb stz $00
909ced dex
909cee bpl $9ceb
909cf0 rep #$20
909cf2 lda #$01
909cf5 sta $00
909cf7 sep #$20
909cf9 lda #$12 ;>alters 909cf2</pre>

**Comment by devinacker** [comment]
Yes, currently instructions are disassembled on an individual basis and the disassembler is only aware of what the _current_ CPU state is, not what it was or would be when editing a previous or future instruction.

Anyway, the current disassembler view is going away after the next release anyway, and I'm pretty sure everything you've mentioned is more or less addressed in it already.
