### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by GhbSmwc** [devinacker/bsnes-plus#176]
For some reason, when I start up bsnes plus a messaged appeared (I couldn't remember) saying these software crashed (all I remember directX), so I closed the software and try to rerun it again and for some reason, won't run any games on it, just a black screen with a framerate saying 120 frames per second. I reinstalled the software still no luck. I even tried to restart my PC and still no luck.

**Comment by devinacker** [comment]
Did you remember to follow the directions in the error message afterwards?

>**Warning:**
>bsnes crashed while attempting to initialize device drivers the last time it was run.
>
>To prevent this from occurring again, all drivers have been disabled. Please go to Settings->Configuration->Advanced and choose new driver settings, and then restart the emulator for the changes to take effect. _Video, audio and input will not work until you do this!_

**Comment by GhbSmwc** [comment]
Yes, it worked! (it now runs games) So it said that some of the drivers crashed and so it got disabled. Thanks for adding a crash protection measure, because some software might corrupt things when it crashes.
