### ISSUE TITLE
feature request add specific path for game specic roms like dsp or cx4

### ISSUE THREAD

**Issue by jjfmz42015** [devinacker/bsnes-plus#177]
feature request add specific path for game specic roms like dsp

**Comment by jjfmz42015** [comment]
right now when using roms that are not concatenate the game specific chip dumps must be in the games folder. it would be alot cleaner if we could have a "firmware" directory in the bsnes home dir with these files.

current dev builds of higan do this, bsnes-mcfly does this and bizhawk does this.


Just a suggestion that I think would be a great addition to bsnes plus.

**Comment by devinacker** [comment]
Yeah, there probably should be an option for a firmware directory in addition to the other configurable directories. I'll throw this in sometime soon.
