### ISSUE TITLE
IPS patches not loading

### ISSUE THREAD

**Issue by tehlux** [devinacker/bsnes-plus#179]
I'm currently doing some romhacking and using bsnes-plus for debugging, but the IPS patching seems to be a bit .. inconsistent (and currently I'm not even sure it worked at all).

I have rom.smc and rom.ips in the same directory and no other files in there.

I have built bsnes-plus directly from github source (under linux) couple of weeks ago (version is bsnes-plus v073+3a)

In settings it says it will load IPS from path "Same as loaded game", which should be ok.

At the bottom / status bar it says "loaded [rom], and applied IPS patch" but the patch isn't applied in the game (it is in ZSNES for instance and shows up, I changed the colours of some menus, it's a really simple patch that overwrites like 14 bytes in a range, ie "PATCH [address] [len] [bytes] EOF").

In bsnes it seems to load the stock rom and ignore the IPS.

When I apply the patch to the rom (ie change the rom) the changed rom works (ie the changes from the patch are in the game, menu has different colour).

I have read https://github.com/devinacker/bsnes-plus/releases and it says

"Improved BPS/UPS/IPS soft patching support [mziab, Revenant]"

But that should predate my build of bsnes-plus (the timestamp on my binary is Apr 25 2018).

Is this a bug or am I doing something wrong?

**Comment by tehlux** [comment]
I've had a look at the code and it seems applyIPS (bsnes/ui-qt/cartridge/cartridge.cpp) is executed and returns true (since the status bar says "and applied IPS patch"). The reading of the patch in applyIPS (address, length, payload) seems to be correct, too. Would have to check if the array data is altered by the function. I have only superficial knowledge of C++ so I have to think hard / read up on * and & to follow in detail if the writing of  outdata and copying over to data is happening correctly (ie data which is altered by the applyIPS call).

**Comment by tehlux** [comment]
I figured it out.

I have checked whether the data is altered by applyIPS. I made a copy of data before applyIPS is called and then compared it to data after it the call. It differed in the correct offsets (the IPS I've used here writes 1 byte at 0xf19 and 0xf1f each, so two bytes are changed). The data after calling applyIPS contains the correct bytes in these places. But when I take a look at what was in these places before I get completely different bytes, not the ones that are in the stock rom at offset 0xf19 and 0xf1f but which are at offsets 0x1119 and 0x111f instead. so the offsets of the patch and the data loaded from the rom don't match up, they differ by 0x200 (the famous header size). So the rom is loaded into data without the header, but bsnes assumes the patch refers to a headerless rom, which is odd because just after applying the patch there's this code

  //remove copier header, if it exists
  if((size & 0x7fff) == 512) memmove(data, data + 512, size -= 512);

That should happen before applyIPS probably? At the point where applyIPS is called, the first 0x200 bytes of data should still be the header for the patch to work properly (unless its intended like that, I guess it's convention but I thought patches should be written for roms with 0x200 length headers?)

**Comment by devinacker** [comment]
Yeah, I just noticed prior to your edit that there was still that extraneous header removal there. `Reader::direct_load` is only called when the snesreader plugin is not present; the same code also existed in the snesreader plugin before being moved into the main frontend but for some reason the fallback version wasn't modified.

> (I guess it's convention if patches should be applied to roms with header or without).

That depends entirely on whether or not one existed in the ROMs used to create the patch.
