### ISSUE TITLE
SA1 disassembler reads from S-CPU bus

### ISSUE THREAD

**Issue by awjackson** [devinacker/bsnes-plus#18]
When disassembling the SA1's instruction stream, the disassembler reads from the S-CPU bus rather than the SA1's. This usually doesn't matter because opcodes are generally in ROM and ROM is mapped the same way on both buses, but if an instruction fetches, say, an indirect pointer from an address that is WRAM on the S-CPU side but IRAM on the SA1 side, the disassembler will end up displaying the wrong effective address.

Recommended fix is to pull https://github.com/awjackson/bsnes-classic/commit/e9270862cea56a811fe2d1e6e9fe81f287fbd88e and in `SA1Debugger` override `disassembler_read(uint32)` with a method that reads the correct bus.

Also, using vbrbus for debugger access the way you've been doing is problematic. vbrbus isn't just sa1bus without the MMIO; it also doesn't implement ROM bank switching (and based on Nintendo docs I suspect this is intentional and correct, not an oversight by byuu. It's hard to tell, though, because I haven't been able to find a single game that uses the VBR registers...)

**Comment by devinacker** [comment]
I had actually noticed the SA1 bus issue from the disassembler before (while poking around with Kirby Super Star debug leftovers, iirc) but never got around to actually making a note of it. Thanks for the reminder, it's been corrected now (as well as the usage of vbrbus, which I meant to change after you added bus_access, but forgot to until now).
