### ISSUE TITLE
Reloading SPC files, and drag-drop SPC files, do not load properly

### ISSUE THREAD

**Issue by jimbo1qaz** [devinacker/bsnes-plus#189]
bsnes-plus v04 on Windows 10 x64

If I load a SPC file via System/Load Cartridge/SNES music dumps, the SPC plays. If I click "System/Reload", the SPC does not reload, and bsnes-plus sits at a black screen.

Similarly, if I drag-drop a SPC into the window, bsnes-plus sits at a black screen.

**Comment by devinacker** [comment]
This is sort of related to a known bug for BS-X and other cart types so might as well fix both

**Comment by jimbo1qaz** [comment]
Thanks for the bug fix, so you have any CI dev builds?

**Comment by devinacker** [comment]
I don't currently, but you could roll the dice with EmuCR's builds whenever they pull this in.
