### ISSUE TITLE
Feature request & color issue fix: Color normalization

### ISSUE THREAD

**Issue by adejr** [devinacker/bsnes-plus#191]
The proper way to normalize SNES 5-bit color values from 15-bit color is to place the three MSB into the LSB when shifting up to get 8-bit values for 24-bit color.

A 5-bit color value ranges from 0 to 31. An 8-bit color value ranges from 0 to 255.

31*8 = 248.

The current implementation is difficult to track down due to the fact the color table is used and this scales colors via rounding before colors are eventually scaled again elsewhere. (?)

The correct implementation however is to place the 3 MSB into the 3 LSB when shifting like so:
r = (r << 3) | ((r >> 2) & 7);

This preserves the bits and allows you to mask away the 3 LSB to recover the exact 5-bit color value. Since shifting right discards the bits, original_r = r >> 3; is equivalent.

I need to research the issue a bit more to come up with the patch needed... most likely some changes to the way the code is currently structured might be ideal as the modern implementation in higan is correct and lossless while the older bsnes implementation is lossy. The higan implementation is also a lot easier to work with due to the slightly different structure where colors are adjusted at different places in the code.

Someone with more knowledge of the code however could likely implement the proper shifting technique with a lot less effort. Elimination of the current rounding in the color table would be a first step to ensure the original bits aren't lost in conversion.

Once finished it might be nice to have an option for "normalize colors" to determine whether the LSB are filled or left "raw" and zeroed.

**Comment by devinacker** [comment]
>The current implementation is difficult to track down due to the fact the color table is used and this scales colors via rounding before colors are eventually scaled again elsewhere. (?)
>
>The correct implementation however is to place the 3 MSB into the 3 LSB when shifting like so:
r = (r << 3) | ((r >> 2) & 7);

Huh? That's how the color table is already generated...  ([bsnes/ui-qt/link/filter.cpp:102](https://github.com/devinacker/bsnes-plus/blob/master/bsnes/ui-qt/link/filter.cpp#L102-L110))

```c++
    unsigned color  //rgb555->rgb888 conversion
    = ((i & 0x7c00) << 9) + ((i & 0x7000) << 4)
    + ((i & 0x03e0) << 6) + ((i & 0x0380) << 1)
    + ((i & 0x001f) << 3) + ((i & 0x001c) >> 2);

    signed l;
    signed r = (color >> 16) & 0xff;
    signed g = (color >>  8) & 0xff;
    signed b = (color      ) & 0xff;
```

Aside from the (optional) contrast/gamma/etc. adjustments that can take place afterwards (and assuming no filter), those normalized RGB values are exactly what is rendered to the screen. Am I missing something?

**Comment by adejr** [comment]
> uh? That's how the color table is already generated... (bsnes/ui-qt/link/filter.cpp:102)

> Aside from the (optional) contrast/gamma/etc. adjustments that can take place afterwards (and assuming no filter), those normalized RGB values are exactly what is rendered to the screen. Am I missing something?

Perhaps... I'm not sure I've fully identified what the issue is yet.

I know the values given are not lossless with neutral color settings. Masking the LSB from the colors doesn't always produce matching 15-bit color values.

One issue may be an off-by-one error introduced due to "round to nearest, 1/2 = up" in place of truncate mode in the light_table[].

```
double luma = (double)l / 15.0;
unsigned ar = (luma * r + 0.5);
unsigned ag = (luma * g + 0.5);
unsigned ab = (luma * b + 0.5);
light_table[l][(r << 10) + (g << 5) + b] = (ab << 10) + (ag << 5) + ar;
```

If so (1 * 1 + 0.5) would == 2. This could be alleviated using floor(luma * component + 0.499999) but the accuracy would be much higher if the luma scaling were applied after conversion to a higher bitdepth rather than applied at 5-bit depth anyway... but accuracy aside that isn't my issue anyway.

I'll need to do some tests using grayscale palette to double-check the output values for every value 0 to 31

**Comment by adejr** [comment]
Or obviously std::trunc() if c++11 is okay.

**Comment by adejr** [comment]
Now testing with the GDI display option I'm getting the expected values.

So obviously whatever problem I had before wasn't due to anything about the core implementation. Sorry for wasting your time!  

This also verifies that truncation is being used in the case I speculated about above... although it isn't a "very safe" assumption it's a valid one according to spec to my knowledge.

**Comment by adejr** [comment]
I can't reproduce any similar issue with any available video interface so I'd bet it was on the user end... AKA the user.

**Comment by devinacker** [comment]
>So obviously whatever problem I had before wasn't due to anything about the core implementation. Sorry for wasting your time!

No worries, I'm always willing to check things out if they don't seem quite right.

You make a good point about the actual brightness scaling though, I might compare that against current higan just to see if they're doing anything differently there.

**Comment by adejr** [comment]
They are. The higan code uses 16 bits per component which provides 11 bits of fractional precision when the luma is applied.

You can find this in /higan/sfc/interface/interface.cpp along with commentary about the analog video circuit producing "zero is not zero" where the luma (my speculation:) is possibly allowed to leak through the multiplier, I'd need to look at the circuit to understand it in any detail but speculation is speculation.

Observation of the real SNES hardware shows luma = 0 does not produce pure black but a very dimly lit screen instead. They use the value 0 = 1 / 64 which I'd assume is a fudge factor but likely close enough.

These values are then output at 32 bits per component (I'm not sure why) to /higan/video/video.cpp setPalette() where they're read in again as 16 bit per component and the colortable is generated from sat/gamma/luma and finally reduced to 8 bit per component before being sent to the output plugin.
