### ISSUE TITLE
Color Adjustment is baked into screenshots regardless of "Save Unfiltered Screenshots" option

### ISSUE THREAD

**Issue by torridgristle** [devinacker/bsnes-plus#198]
https://i.imgur.com/uuptjPv.png

What was expected to happen is that "Save Unfiltered Screenshots" would cause all screenshots to be unmodified, virtually raw, data without fragment shaders or color adjustments baked in. What did happen is every screenshot has the simulated CRT gamma curve baked in.

If you don't want shaders visible in screenshots, you probably don't want your gamma adjustments and such in them either. None of these screenshots I've taken can be used on MobyGames or used for reference--they're all inaccurate to the source data.

This is why I believe "Save Unfiltered Screenshots" should not have Color Adjustment options baked into the screenshots. Or at the very least another option for Save Raw Screenshots next to Save Unfiltered Screenshots or Disable in Screenshots in the Color Adjustment section or similar.

**Comment by torridgristle** [comment]
I can't edit the above post, so excuse the additional post.

It also doesn't specify that it's referring to shaders specifically since, to me, color adjustments made without using a custom fragment shader falls into the broader term filtering.

This happens with every video driver including null which I got a little kick out of. I wasn't expecting that to take screenshots.

**Comment by devinacker** [comment]
Good call. I'll change unfiltered screenshots to ignore `colortable` and just use the raw input colors, not sure how that hadn't occured to me before (the ideal you're describing is how it was intended to behave, anyway, the use of `colortable` even for unfiltered screenshots was just an oversight on my part when accepting the patch).

**Comment by torridgristle** [comment]
Is there an AppVeyor or something to get this from? Haven't got all the requirements set up and I'd rather wait for the next official release than get all of it up and running.

**Comment by devinacker** [comment]
Not officially (yet), but EmuCR.com at least has unofficial daily-ish builds.
