### ISSUE TITLE
Tile Replacement

### ISSUE THREAD

**Issue by ADormant** [devinacker/bsnes-plus#20]
Hi, this is a very interesting feature, I wonder if it could be done in bsnes-plus? Currently only HDNes is capable of doing it. https://github.com/mkwong98/HDNes Description http://www.1emulation.com/forums/files/file/23-hdnes/
https://github.com/shonumi/gbe-plus/wiki/Project-Goals
http://code.google.com/p/gb-enhanced/
![hd tiles](https://cloud.githubusercontent.com/assets/10523326/7903277/d0c928a0-07d6-11e5-9ded-3a2d75f8c454.jpg)

**Comment by devinacker** [comment]
It would be very non-trivial to add something like this to bsnes even for NES graphics, and there are many things the SNES has for graphics that the NES doesn't that would make the implementation much more complicated anyway.
