### ISSUE TITLE
Sprite Viewer Enhancement

### ISSUE THREAD

**Issue by torridgristle** [devinacker/bsnes-plus#200]
Unlike the Tile Viewer or the Map Viewer, the Sprite Viewer only gives you single pieces of the larger graphics on-screen. I propose a preview area like the Map Viewer that shows you all sprites on the screen and you can click on sprites to view their info and you can right click on them to disable them in the viewer, and right click and drag for a rectangular selection or lasso selection which may be better for some messier scenes, which can be shown as transparency. Then you can export the Sprite Viewer window or you can export the enabled sprites pieced together instead of the whole window.

Some of this can potentially be automated. For example, Kyuuyaku Megami Tensei has characters made of 16x16 sprites and each sprite is aligned to + or - 16px of each other. Nothing else is touching it. It seems like this grid-aligned sprite-touch detection would work with many games while being a simple concept, as for being simple to program I don't know but I hope so. A toggle for guessing connected sprites in the Sprite Viewer would give people the option to quickly turn it off and keep it off when they encounter a problem area.

Remembering which sprites are disabled and which are connected and which new sprites in the refresh are connected to enabled or disabled sprites between refreshes would speed things along since sprites don't need to be disabled over and over, and some elements can be left automated.

**Comment by devinacker** [comment]
see #150
