### ISSUE TITLE
Sprite Ripping

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#202]
The new Tile Viewer and Tilemap Viewer dialogs make it really easy to extract BG layers with transparency intact, but there currently isn't any way to do the same with sprites.  I think probably the easiest place to add it to the GUI would be in the Tilemap Viewer, just add a "sprite" layer button next to the current 1-4 buttons, which would make the sprite layer visible and allow you to extract all of the currently displayed sprites in one go, but it could also be added into the Sprite Viewer as well to extract individual sprites.

**Comment by undisbeliever** [comment]
I'll take a stab at it.

I've got some crazy idea involving QAbstractItemModel, QItemSelectionModel and QGraphicsScene that will create a new *Sprite Viewer* GUI that will allow you:

 * View the sprites in a graphics view
 * View the sprite data in a sortable table
 * Select the sprites using the graphics view or table view
 * Hide sprites from the graphics view
 * Save the graphics view as a png image

I'll sketch something more manageable on paper tonight and work on it tomorrow. Expect something usable by the weekend.

**Comment by undisbeliever** [comment]
Here is what I have got so far. You can see my progress at https://github.com/undisbeliever/bsnes-plus/tree/new-oam-viewer

Design decisions:
 * Y axis wrapped sprites are shown twice. Once in the location displayed in the table and on the location displayed on screen.
 * The background color can be selected from a list of options. The default is transparent to assist with sprite ripping.
 * A rectangle showing the screen outline has been added to  illuminate the sprite's locations relative to the screen. I've added a checkbox to disable it so partially offscreen sprites can be ripped.

Still to do:
 * [ ] Object selection using the mouse in OamGraphicsScene
 * [ ] Show/hide objects menu/button to assist in sprite ripping
 * [ ] Determine if the screen height is 224 or 240 pixels tall
 * [ ] Determine which object is the first sprite when Sprite priority rotation is activated (bit 7 of 0x2103)
 * [ ] Test the new Sprite Viewer in Windows

I'm going to be busy the first half of the week, expect the next set of updates to occur later in the week.

Paging @qwertymodo: can you please let me know your thoughts on the UI design and if there is any functionality you think I may be missed.


Screenshots:
![y-axis-wrapping](https://user-images.githubusercontent.com/65687/48671142-7fa1af80-eb6f-11e8-9fa4-5b05c4bfaf42.png)

It also works on the qt5 branch.
![screenshot-qt5](https://user-images.githubusercontent.com/65687/48671073-76fca980-eb6e-11e8-83fc-ff0517a72f86.png)

And the exported images created by the new Sprite Viewer:
![illusion of time](https://user-images.githubusercontent.com/65687/48671074-7bc15d80-eb6e-11e8-8328-a39e3279432f.png)
![yoshi s island titlescreen](https://user-images.githubusercontent.com/65687/48671090-d064d880-eb6e-11e8-8da7-448e5eea400d.png)

**Comment by qwertymodo** [comment]
Looks good so far!  I'm not much use in UI design, but your Tile Viewer redesigns have worked great, so I have full confidence in what you'll come up with.

**Comment by undisbeliever** [comment]
Sorry for the delay. I got hit by a heat wave and both myself and my equipment overheated for about a week.

The new Sprite Viewer is now feature complete. (https://github.com/undisbeliever/bsnes-plus/tree/new-oam-viewer)

I am yet to test it on a Windows machine. When I have time to spin-up a Windows VM (which is most likely Friday) and confirm everything works I'll submit a push request.

---

New features include:
 * Screen outline height is either 224 or 239 pixels depending on the state of the overscan PPU register.
 * Multiple objects can now be selected in either the table view or the graphics view.
 * Objects in the Sprite Viewer can now be hidden. This can be done one of two ways:
    * Clicking on the checkbox in the table
    * Right clicking in the table/graphics and selecting an action from the context menu.
![before-cropped](https://user-images.githubusercontent.com/65687/49511891-1bede500-f8d8-11e8-8cf2-f2285f2f7e63.png)
![after-cropped](https://user-images.githubusercontent.com/65687/49511912-2ad49780-f8d8-11e8-8423-5409f952e240.png)
![will-running-right](https://user-images.githubusercontent.com/65687/49511899-227c5c80-f8d8-11e8-8d40-74d97dcd7829.png)

 * Sprite priority rotation.
   To test that sprite priority rotation works correctly I modified the unit tests of the untech-engine to rotate the sprites every frame and manually compared the results.
![first-sprite-test](https://user-images.githubusercontent.com/65687/49511930-3d4ed100-f8d8-11e8-9c43-3b5e340d2c00.png)

**Comment by undisbeliever** [comment]
It took a lot longer than expected but I have finally got a windows VM running.

There was a compile error when building my code in Windows, which required a simple fix (commit e94be79).

The new Sprite Viewer has been tested in Windows 7 with Qt 4.8.6 and Qt 5.9 and it works perfectly. I'm writing up the PR now.

**Comment by devinacker** [comment]
feature merged in #207
