### ISSUE TITLE
Display Selected Tile Address in the Tilemap Viewer

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#208]
In the Tilemap Viewer, if you click on a tile, it displays the VRAM address corresponding to that tile's entry in the tilemap, and the value at that address, corresponding to a tile index relative to the base address for the given layer.  However, it doesn't show the actual address of that tile in VRAM, which would be really helpful when trying to correlate tiles on screen with tiles in VRAM.  Can we add that?

![tileaddress](https://user-images.githubusercontent.com/5988870/50305001-76de1b00-0446-11e9-8ae3-10c784b05eff.png)

**Comment by undisbeliever** [comment]
I've coded and submitted a pull request that adds a "Char Address" field to the Tilemap Viewer. (PR #209)

**Comment by devinacker** [comment]
merged that PR
