### ISSUE TITLE
Freeze on startup...

### ISSUE THREAD

**Issue by radioraptor** [devinacker/bsnes-plus#213]
Ran across this strange issue of program freezing if ANY input plugin is selected before launch...

Haven't got the foggiest idea why...

**Comment by devinacker** [comment]
That's unfortunate. I take it that it doesn't freeze if no input is in use?

What version / OS are you running?

**Comment by radioraptor** [comment]
Yes that is correct. It has become the workaround to not enable any input...

I'm running version 04 (Jun 18 2018) on windows 10 pro.

**Comment by devinacker** [comment]
Do older releases (v3 or earlier) have the same issue? What about running in a compatibility mode for an earlier version of Windows?

I don't really have an easy way to test on win10 at the moment, unfortunately...

**Comment by radioraptor** [comment]
Not sure if v3 did...
I did mess about with compatibility mode... didn't really help...

**Comment by devinacker** [comment]
closing due to lack of info, please feel free to reopen with more details
