### ISSUE TITLE
Display suggestions

### ISSUE THREAD

**Issue by GhbSmwc** [devinacker/bsnes-plus#215]
My suggestions:

- Make sure that hex number show “0x”, I found one without this prefix on debugger -> S-PPU ->“Tile viewer” (display the tile graphics in memory) and on the bottom of the window, the status bar, have the text “Selected Tile Address”, while the “Tilemap Viewer” (as in, displays the “map” of the tiles used from the viewer (not to be confused with tile viewer)) does display the “0x”

- Show “character number” on the “tile viewer” when selecting a tile. Basically on the “tilemap viewer” its the number with the word “character” appended to it (Character: 252, for example).
![image](https://user-images.githubusercontent.com/13095760/54788058-27091e80-4c04-11e9-9079-3380fcfbe83c.png)
![image](https://user-images.githubusercontent.com/13095760/54788213-a26ad000-4c04-11e9-8214-30bf9b68a297.png)

**Comment by undisbeliever** [comment]
These features have already been implemented with PR #209, "Tilemap character address" (see included screenshots).

As for your second suggestion. It is difficult (from a UI perspective) to convert a tile address to a character address as I do not know what background layer you are currently thinking about.  Instead PR #209 adds a "selected tile address" field to the Tilemap Viewer to make finding tiles easier.

**Comment by GhbSmwc** [comment]
Oh okay, this was tested on SMW on a layer 3.

**Comment by devinacker** [comment]
Closing since this stuff seems to have been basically addressed by the aforementioned (and now merged) PR already
