### ISSUE TITLE
build error ubuntu 

### ISSUE THREAD

**Issue by fpscan** [devinacker/bsnes-plus#217]
`rcc ui-qt/resource/resource.qrc -o obj/resource.rcc
moc -i ../common/nall/qt/check-action.moc.hpp -o obj/check-action.moc
moc -i ../common/nall/qt/file-dialog.moc.hpp -o obj/file-dialog.moc
moc -i ../common/nall/qt/radio-action.moc.hpp -o obj/radio-action.moc
moc -i ../common/nall/qt/window.moc.hpp -o obj/window.moc
moc -i ui-qt/debugger/tracer.moc.hpp -o obj/tracer.moc
moc -i ui-qt/debugger/ppu/oam-graphics-scene.moc.hpp -o obj/oam-graphics-scene.moc
moc -i ui-qt/debugger/ppu/image-grid-widget.moc.hpp -o obj/image-grid-widget.moc
moc -i ui-qt/debugger/ppu/tilemap-viewer.moc.hpp -o obj/tilemap-viewer.moc
moc -i ui-qt/debugger/ppu/oam-viewer.moc.hpp -o obj/oam-viewer.moc
moc -i ui-qt/debugger/ppu/oam-data-model.moc.hpp -o obj/oam-data-model.moc
moc -i ui-qt/debugger/ppu/tile-viewer.moc.hpp -o obj/tile-viewer.moc
moc -i ui-qt/debugger/ppu/cgram-viewer.moc.hpp -o obj/cgram-viewer.moc
moc -i ui-qt/debugger/ppu/cgram-widget.moc.hpp -o obj/cgram-widget.moc
moc -i ui-qt/debugger/tools/properties.moc.hpp -o obj/properties.moc
moc -i ui-qt/debugger/tools/qhexedit2/qhexedit.moc.hpp -o obj/qhexedit.moc
moc -i ui-qt/debugger/tools/qhexedit2/commands.moc.hpp -o obj/commands.moc
moc -i ui-qt/debugger/tools/disassembler.moc.hpp -o obj/disassembler.moc
moc -i ui-qt/debugger/tools/breakpoint.moc.hpp -o obj/breakpoint.moc
moc -i ui-qt/debugger/tools/memory.moc.hpp -o obj/memory.moc
moc -i ui-qt/debugger/registeredit.moc.hpp -o obj/registeredit.moc
moc -i ui-qt/debugger/debugger.moc.hpp -o obj/debugger.moc
moc -i ui-qt/tools/effecttoggle.moc.hpp -o obj/effecttoggle.moc
moc -i ui-qt/tools/cheateditor.moc.hpp -o obj/cheateditor.moc
moc -i ui-qt/tools/tools.moc.hpp -o obj/tools.moc
moc -i ui-qt/tools/soundviewer.moc.hpp -o obj/soundviewer.moc
moc -i ui-qt/tools/statemanager.moc.hpp -o obj/statemanager.moc
moc -i ui-qt/tools/cheatfinder.moc.hpp -o obj/cheatfinder.moc
moc -i ui-qt/tools/manifestviewer.moc.hpp -o obj/manifestviewer.moc
moc -i ui-qt/application/application.moc.hpp -o obj/application.moc
moc -i ui-qt/base/about.moc.hpp -o obj/about.moc
moc -i ui-qt/base/htmlviewer.moc.hpp -o obj/htmlviewer.moc
moc -i ui-qt/base/stateselect.moc.hpp -o obj/stateselect.moc
moc -i ui-qt/base/loader.moc.hpp -o obj/loader.moc
moc -i ui-qt/base/main.moc.hpp -o obj/main.moc
moc -i ui-qt/base/filebrowser.moc.hpp -o obj/filebrowser.moc
moc -i ui-qt/settings/input.moc.hpp -o obj/input.moc
moc -i ui-qt/settings/paths.moc.hpp -o obj/paths.moc
moc -i ui-qt/settings/settings.moc.hpp -o obj/settings.moc
moc -i ui-qt/settings/advanced.moc.hpp -o obj/advanced.moc
moc -i ui-qt/settings/video.moc.hpp -o obj/video.moc
moc -i ui-qt/settings/bsx.moc.hpp -o obj/bsx.moc
moc -i ui-qt/settings/profile.moc.hpp -o obj/profile.moc
moc -i ui-qt/settings/audio.moc.hpp -o obj/audio.moc
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/main.cpp -o obj/ui-main.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/base/base.cpp -o obj/ui-base.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/cartridge/cartridge.cpp -o obj/ui-cartridge.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/debugger/debugger.cpp -o obj/ui-debugger.o
In file included from ui-qt/debugger/debugger.cpp:14:
ui-qt/debugger/tools/memory.cpp: In member function ‘void MemoryEditor::showAddress(qint64)’:
ui-qt/debugger/tools/memory.cpp:169:17: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘qint64’ {aka ‘long long int’} [-Wformat=]
     msg.sprintf("Address: 0x%06X", address);
                 ^~~~~~~~~~~~~~~~~  ~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-absolute-value’
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/input/input.cpp -o obj/ui-input.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/movie/movie.cpp -o obj/ui-movie.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/settings/settings.cpp -o obj/ui-settings.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/state/state.cpp -o obj/ui-state.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -Iobj `pkg-config --cflags QtCore QtGui` -c ui-qt/tools/tools.cpp -o obj/ui-tools.o
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -DVIDEO_GLX -DVIDEO_XV -DVIDEO_QTRASTER -DVIDEO_SDL -DAUDIO_ALSA -DAUDIO_OPENAL -DAUDIO_OSS -DAUDIO_PULSEAUDIO -DAUDIO_PULSEAUDIOSIMPLE -DAUDIO_AO -DINPUT_SDL -DINPUT_X `sdl-config --cflags` `pkg-config --cflags QtCore QtGui` -c ruby/ruby.cpp -o obj/ruby.o
In file included from ./ruby/ruby_impl.cpp:123,
                 from ruby/ruby.cpp:6:
./ruby/audio/openal.cpp:11:12: fatal error: AL/al.h: No such file or directory
   #include <AL/al.h>
            ^~~~~~~~~
compilation terminated.
make: *** [ui-qt/Makefile:87: obj/ruby.o] Error 1
gadsby@ubuntu:~/bsnes-plus/bsnes$ sudo make
g++ -std=gnu++0x -I. -I../common -Isnes -O3 -fomit-frame-pointer -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -DPROFILE_COMPATIBILITY -DDEBUGGER -DVIDEO_GLX -DVIDEO_XV -DVIDEO_QTRASTER -DVIDEO_SDL -DAUDIO_ALSA -DAUDIO_OPENAL -DAUDIO_OSS -DAUDIO_PULSEAUDIO -DAUDIO_PULSEAUDIOSIMPLE -DAUDIO_AO -DINPUT_SDL -DINPUT_X `sdl-config --cflags` `pkg-config --cflags QtCore QtGui` -c ruby/ruby.cpp -o obj/ruby.o
In file included from ./ruby/ruby_impl.cpp:123,
                 from ruby/ruby.cpp:6:
./ruby/audio/openal.cpp:11:12: fatal error: AL/al.h: No such file or directory
   #include <AL/al.h>
            ^~~~~~~~~
compilation terminated.
make: *** [ui-qt/Makefile:87: obj/ruby.o] Error 1
`

I am trying to build it on brand new ubuntu however this what happen, any idea?

**Comment by fpscan** [comment]
https://pastebin.ubuntu.com/p/yWNywfstcb/

**Comment by devinacker** [comment]
Have you installed `libopenal-dev` as mentioned in the build instructions?

**Comment by devinacker** [comment]
closing due to lack of info
