### ISSUE TITLE
Can't run the with new update, after compile.

### ISSUE THREAD

**Issue by Csokis** [devinacker/bsnes-plus#229]
Today compiled the code after git pull, can't working anymore (SEGFAULT). :-( Here is the debug information:

> [Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

> Program received signal SIGSEGV, Segmentation fault.
> __strcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:534
> 534	../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
> (gdb) 

**Edit:** Xubuntu 18.04.3 LTS

**Comment by devinacker** [comment]
What happens if you run `make clean` first and then try again?

**Comment by Csokis** [comment]
Same. I deleted the whole thing, then git clone, but same again. :-(

**Comment by devinacker** [comment]
Okay, I think I'm able to reproduce the issue on Ubuntu as well. I'll take a look.

**Comment by devinacker** [comment]
Should be good now, please try to pull again and let me know if you still have any problems.
