### ISSUE TITLE
Enhancement: Any plan of adding xbrz filter support

### ISSUE THREAD

**Issue by CarterLi** [devinacker/bsnes-plus#23]
http://sourceforge.net/projects/xbrz/
AFAIK, [Many](http://sourceforge.net/projects/xbrz/files/?source=navbar) [emulators](http://sourceforge.net/p/vbam/code/HEAD/tree/trunk/src/filters/xbrzfilter.cpp) [already](http://sourceforge.net/p/desmume/code/HEAD/tree/trunk/desmume/src/filter/xbrz.cpp) [support](https://github.com/snes9xgit/snes9x/blob/master/filter/xbrz-config.h) [this](https://github.com/hrydgard/ppsspp/tree/e48f8125843af90d141983474fdd37677d49a101/ext/xbrz) __high quality image upscaling filter__. It should be a good idea that we add it too.

**Comment by devinacker** [comment]
I haven't looked at any of the existing implementations yet, but this seems like it would (ideally) require multithreading (via OpenMP)  for the same reason as hq2x, which may or may not be removed from bsnes-classic later in order to reduce dependencies.

I'll leave this idea on the table for now, but it's not a high priority.

**Comment by CarterLi** [comment]
No, xBRZ itself has nothing to do with __multithreading__, doesn't use OpenMP at all. It's just thread-safe.

I've tried myself to add xBRZ support to _snesfilter_, but failed to make it work...
```C++
// xbrz2x.hpp
class XbrzFilter {
public:
  void size(unsigned&, unsigned&, unsigned, unsigned);
  void render(uint32_t*, unsigned, const uint16_t*, unsigned, unsigned, unsigned);
} filter_xbrz2x;
```
```C++
// xbrz2x.cpp
#include "xbrz.h"
#include "xbrz2x.hpp"
#include "xbrz.cpp"

void XbrzFilter::size(unsigned &outwidth, unsigned &outheight, unsigned width, unsigned height) {
  if(width > 256 || height > 240) return filter_direct.size(outwidth, outheight, width, height);

  outwidth  = 2 * width;
  outheight = 2 * height;
}

void XbrzFilter::render(uint32_t *output, unsigned outpitch, const uint16_t *input, unsigned pitch, unsigned width, unsigned height) {
  if(width > 256 || height > 240) {
    filter_direct.render(output, outpitch, input, pitch, width, height);
    return;
  }
  
  xbrz::scale(2, (const uint32_t *)input, width, height, pitch, (uint32_t *)output, outpitch, xbrz::RGB);
```
Result:
![screenshot 2015-06-02_22-02-28](https://cloud.githubusercontent.com/assets/6134068/7937532/16c1d544-0973-11e5-8081-c497f1c46825.png)

**Comment by Optiroc** [comment]
It seems like you need to swizzle the color channels and (obviously) put in a scaling pass somewhere. But to be honest, if filters are your "thing", more recent bsnes flavours (ie. Higan) or RetroArch has are a much better fit than this specialized fork of bsnes-classic.

**Comment by CarterLi** [comment]
Well, I just want to play my favorite SNES games on my macbook, don't really care which emulator is used. But it seems that Higan & snes9x have dropped OSX support AFAIK.
I don't know how to connect Higan owner. I have tried snes9x on my macbook too, that was awful.
I found bsnes-plus one day on emucr, which says that it have OSX support. So I come here :)

**Comment by Optiroc** [comment]
For "players" [OpenEmu](http://openemu.org) is a pretty good choice. It supports GLSL shaders and has a much more approachable UI than RetroArch.

But then again, bsnes-plus is devinacker's work and it's obviously up to him what features to add. But I don't think I'm mistaken when I'm saying it's *"not for the players"*. (:

**Comment by CarterLi** [comment]
Yes, OpenEmu has an approachable UI, but nothing else. OpenEmu lacks too many necessary features for a good emulator: Only one quick save supported per game; no battery save importer; no auto-hold, rapid-fire, no memory viewer, no cheat searcher. Yes it supports shaders, but doesn't support xBRZ ( both vba-m, desmume and snes9x support it ) which is my favorite.
I'd rather use the original emulators than their cores with a beautiful skin.

**Comment by CarterLi** [comment]
As my PR has been rejected due to imcompatible licenses, this feature can't be implemented in a simple way.
I'll maintain my implementation in my own fork. Closing this one
