### ISSUE TITLE
Emulator doesn't run games after weird error

### ISSUE THREAD

**Issue by weierstrass1** [devinacker/bsnes-plus#231]
I was using the bsnes+ debugger, all was fine until an error message appears with something about direct x, i pressed accept and the bsnes stop to work, then it didn't work again, i tried to redownload the emulator, but it still doesn't work. I cant play any game now on bsnes+. I have direct X 12

**Comment by devinacker** [comment]
Is this the error you're talking about?

![](https://i.imgur.com/Z4QK62G.png)

Like the dialog says, you'll need to re-configure your audio/video/input settings and restart the emulator.

If you do this and you're still having issues with DirectX, please let me know.
