### ISSUE TITLE
latest dev version download?

### ISSUE THREAD

**Issue by jjfmz42015** [devinacker/bsnes-plus#232]
Is there anywhere I can download the latest dev version? Found it on emucr however it only complies compatibility exe not accuracy

**Comment by jjfmz42015** [comment]
or can someone help me build it? im stuck

**Comment by devinacker** [comment]
I'm working on setting up AppVeyor for both 64-bit compatibility and accuracy builds. You can now grab a fresh one here: https://ci.appveyor.com/project/devinacker/bsnes-plus/build/artifacts

**Comment by jjfmz42015** [comment]
Thank you!!
