### ISSUE TITLE
vramexpand vs master

### ISSUE THREAD

**Issue by jjfmz42015** [devinacker/bsnes-plus#235]
Looking at appveyor release until 5.15 they were master releases, 5.16 is vram expand.

What version should I use. I dont know enough to understand if vram expand is a special situation or just the way going forward.

Thanks

**Comment by devinacker** [comment]
vramexpand is still just a feature branch for now, although all of the recent commits from the master branch have been merged into it as of that build. The vramexpand branch will be merged back into master once it's "done" (soon, hopefully).

The build numbers on AppVeyor are just based on the number of times that the automated build has been run (i.e. the 15th build was from the master branch, the 16th time was from the vramexpand branch).

The master branch is still the "official" one unless you're wanting to use something that's exclusive to a feature branch.

**Comment by jjfmz42015** [comment]
thank you very much.
