### ISSUE TITLE
Phantom instructions in disassembly view when subroutine changes processor flags

### ISSUE THREAD

**Issue by randomdude999** [devinacker/bsnes-plus#239]
When the X flag is clear and you call a subroutine that sets it, there will occasionally (after immediate loads, that is) be "phantom instructions" in the disassembly view that will be skipped over by actual execution. Here is an example:

```
org $8000
main:
clc
xce
rep #$10
jsr asub
ldy #$0f
sty $0100
lbl: bra lbl

asub:
sep #$10
rts

org $fffc
dw main
```

When stepping through, there will be a phantom `brk #$01` after the `sty $0100`:
![image](https://user-images.githubusercontent.com/10598847/69915065-84bc5e80-1453-11ea-96a5-0abc19450dac.png)
![image](https://user-images.githubusercontent.com/10598847/69915072-9998f200-1453-11ea-83b7-4e11ddae6a00.png)

**Comment by devinacker** [comment]
Looks like a bug in `CPUAnalyst::performAnalysis` not always tracking register sizes across calls like it should be. I'll take a look shortly.

**Comment by devinacker** [comment]
Should be okay now, let me know if you notice any other similar weirdness.
