### ISSUE TITLE
Feature Request: SGB debugging

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#241]
It would be nice to add debugging capabilities for the DMG side of the Super GameBoy.

- CPU tracing
- Disassembly
- Memory viewer
- Breakpoints
- Register viewer

**Comment by devinacker** [comment]
I've had the same thought for a while now, but I'm not sure how feasible it would be with the way that the SGB plugin currently works. It might be worthwhile to try adding some additional stuff to the plugin interface (memory/register access, a step callback, etc) to facilitate that though.

**Comment by devinacker** [comment]
SGB memory viewing/editing is now in. Hopefully will be able to work on some actual disassembly/debugging soon as well.

**Comment by devinacker** [comment]
More stuff is now in the `sgbdebug` feature branch. Currently in place now:
* GB memory viewing/editing
* GB CPU disassembly
* GB CPU register/flag viewing/editing
* GB CPU single stepping and read/write/exec breakpoints

Stuff I'll still need to do:
* Call/return tracking to enable step-out and step-over
* Symbol support, prettier disassembly and static analysis (to match the other debuggers)
* ???

AppVeyor has the branch if you want to try it out. If this stuff seems to work fine as-is I'll probably go ahead and merge it into master soon.

**Comment by qwertymodo** [comment]
It would be nice to have Super GB cart ROM/RAM as a breakpoint source.  I see it's already available in the Memory Editor.

**Comment by devinacker** [comment]
All the currently existing SGB stuff is merged into master now, so I'll close this and let SGB feature discussion continue in #249.
