### ISSUE TITLE
Super Gameboy msu bug

### ISSUE THREAD

**Issue by Conn79** [devinacker/bsnes-plus#243]
http://helmet.kafuka.org/bboard/thread.php?pid=5235#5235

When trying this example 

> Here it is an example:

>https://drive.google.com/open?id=1EDqWU8-obQqoOPlMiPVcgenxBcuf2eDZ

>- Apply ffa_mute.ips on final fantasy adventure (u) [b1].gb
>- Apply sgbBios.ips on Super Game Boy (World) (Rev 2).sfc
>- Rename Super Game Boy (World) (Rev 2).sfc into sgBios.sfc
>- Take a pcm of your choice and rename it into sgbBios-2.pcm
>- Put the files along with sgbBios.msu into a folder
>- run bsnes plus -> load special -> load super Game Boy Cartridge
>load the sgbBios as base cartridge and the final fantasy as Gameboy cartridge

>You should hear very silent the msu (if you don't try with another pcm (I used dkc_msu-2.pcm)

>For higan you may need a bml, haven't made one yet, so bsnes plus is the emulator of choice for now. 

in bsnes plus, the music is way too silent and the sfx are delayed... However in higan and bsnes 113 it works just fine!

**Comment by devinacker** [comment]
As mentioned on Discord a few days ago, I think this is just a limitation of the audio mixing only supporting one external audio source at a time. Shouldn't be much work to backport the more flexible mixing from current bsnes though, so I'll try to do that sometime after the new year.

**Comment by devinacker** [comment]
Multiple expansion audio sources are now supported as of 8ca9b3c3c277c6f6489d3ff3accce05e9ee79f72. Seems to work fine with a quick test of qwertymodo's Final Fantasy Adventure patch.
