### ISSUE TITLE
Pixel Shader not working

### ISSUE THREAD

**Issue by RokkumanX** [devinacker/bsnes-plus#244]
Hi and thanks for a wonderful fork of bsnes!

There seems to be something wrong with Pixel Shaders, can't seem to be able to load the specific .shader I want from here:

https://gitlab.com/higan/xml-shaders/blob/master/shaders/OpenGL/v1.1/SimpleTVBlur.OpenGL.shader

Description:

> Simple TV Blur, by Themaister

    This shader uses linear-filtering horizontally, and point-filtering
    vertically, to approximate the effect of a CRT's raster scan. It also
    blends the source image down to 256px across, which should cause SNES games
    that use hires or psuedo-hires modes to look 'right' even in bsnes'
    Accuracy and Performance cores, which don't blend pixels internally.

    This is also about the most complete TV emulation you can get that just
    uses scale and filter attributes, without writing any shader code. :)

I want to use this specific shader to make Kirby 3 look OK in bsnes.

Is the .shader in wrong format? Is .shader loading broken?

I am using OpenGL as the .shader name suggests and most of the bsnes settings is default.

**Comment by devinacker** [comment]
As I recall, there were some changes to the XML shader format after bsnes v073 which probably never made their way downstream (for instance, being able to specify multiple fragment shaders in the same file, which a lot of the ones in that repo do, including the one you linked). I'll have to see about updating shader loading at some point to support those changes.

**Comment by RokkumanX** [comment]
Most appreciated, thanks for all your work on this fork!

**Comment by RokkumanX** [comment]
I'm closing this issue, you know what's wrong and there is no need for this to stay open.
Besides I have moved on so this isn't a game breaker.
