### ISSUE TITLE
Super Game Boy - $6000/$6001/$7800 emulation issues

### ISSUE THREAD

**Issue by Bananattack** [devinacker/bsnes-plus#247]
Hi there! I'm currently working on a homebrew test program for the Super Game Boy that can upload custom SNES code and then use the Super Game Boy / ICD2 ports to read the GB screen's VRAM data.

I realize that this won't affect any commercial games, but I noticed the current emulation has a few issues that limit things to only work if exactly as they're laid in the stock Super Game Boy BIOS.

How it should work:
- The VRAM contains 4 row-sized buffers of 320 bytes (16 bytes * 20 tiles), and every time a new tile rows is rendered, the buffer index that the GB PPU writes into is incremented. Every 8 lines, the next buffer is used. There are 18 rows total (144 / 8) per screen, and 18 rows / 4 buffers = 4 remainder 2. So, each frame will start on either buffer index 0 or 2, depending on which frame it is.
- Reading port $6000 gives which current tile row is being rendered (upper 5 bits, aka bits 7 .. 3), as well as which of the buffers 0 .. 3 is being written into currently (lower 2 bits, aka bits 1 .. 0).
- Writing to port $6001 can select which of the buffers 0 .. 3 to use, and doing so will reset the reader position in the buffer when read with $7800.
- Reading port $7800 returns the next byte in the currently selected buffer, and auto-increments. It can be read directly, or as the SGB BIOS does, you can use DMA to copy things into WRAM (or another Bus B destination).

How it currently works in bsnes-plus:
- Reading port $6000 currently returns the current GB scanline, but this is incorrect. (The upper 5 bits should indicate the the tile row being rendered. The lower 2 bits should indicate which buffer is being written.)
- Writing to port $6001 currently does nothing.
- The Super Game Boy emulation currently intercepts writes to SNES registers WMADDL ($2181) / WMADDM ($2182) and MDMAEN ($420B) to determine which row is to be read. In bsnes-plus, the WRAM address selected must be some 320-byte aligned offset relative to $7E5000 or to $7E6800, and DMA must be requested on channel 4, otherwise the emulation won't update the VRAM buffer and $7800 will return incorrect values. https://github.com/devinacker/bsnes-plus/blob/acc33048258bf762e6e74108c9c392210173dd2e/bsnes/snes/chip/supergameboy/supergameboy.cpp#L55-L73
- As a result, reading port $7800 directly doesn't work unless you do DMA + the program puts buffer in the exact same RAM location as the SGB BIOS. In reality, DMA is optional, and WRAM address shouldn't be used to determine which part of the screen will be read.

I've worked around this issue, but this problem doesn't exist in stock bsnes, there might be some code worth migrating (even though bsnes-plus uses Gambatte and bsnes uses Sameboy).

For reference, here is bsnes:
- port $6000 reads: https://github.com/byuu/bsnes/blob/d62e3f3362dad31485c06665d079560a4dfb509c/bsnes/sfc/coprocessor/icd/io.cpp#L4-L7
- port $6001 writes: https://github.com/byuu/bsnes/blob/d62e3f3362dad31485c06665d079560a4dfb509c/bsnes/sfc/coprocessor/icd/io.cpp#L43-L48
- handling of the hblanks, vblanks and PPU rendering: https://github.com/byuu/bsnes/blob/d62e3f3362dad31485c06665d079560a4dfb509c/bsnes/sfc/coprocessor/icd/interface.cpp#L1-L20

If it helps, I can contribute my test ROM with a version that passes on hardware + bsnes but not bsnes-plus, but I just need a bit little more time to clean a few things up! But even without this ROM, I think it should be possible to compare implementation details and hopefully correct some things.

Thanks for the help!

**Comment by devinacker** [comment]
Test ROM would be good, if you're able. I'll look into this soon since I've started working on SGB-related stuff again.

**Comment by Bananattack** [comment]
Okay!

- https://make.vg/get/homebrew/sgb_snes_custom_protocol_framebuffer_7E2000.gb - fails in bsnes-plus. Passes on hardware, bsnes, and higan. Uses DMA to RAM but a different location. ICD2 register $7800 reads should also be allowed directly, and it should work like an auto-incrementing read-only port when used that way.
- https://make.vg/get/homebrew/sgb_snes_custom_protocol_framebuffer_7E5000.gb - passes on hardware, bsnes, higan, and bsnes-plus, because the framebuffer is at the exact same WRAM location as in the SGB BIOS, and I use DMA to transfer the ICD2 framebuffer data into WRAM.
- Here's the source: https://github.com/wiz-lang/wiz/tree/master/examples/gb/sgb_snes_custom_protcol

I recently tried the latest snapshot of the sgbdebug branch and I didn't have any luck running my test ROMs, it would get past the SGB boot up sequence, but never execute the DATA_TRN and JUMP packet takeover, on any test ROM. I'll try to give it another shot though! maybe I missed something!

Here are some other test ROMs if they help:

- https://make.vg/get/homebrew/sgb_snes_upload.gb - Test ROM that resets the SPC back to IPL ROM, uploads a custom 65816 program, and then jumps to it. After that, there's no communication with the GB, but it has custom 65816 and SPC700 code uploaded and running. This works on all emulators with Super Game Boy emulation that I tried, since it doesn't try to communicate with the GB side after the custom SNES code takes over. I couldn't get it to run on sgbdebug branch however.
- Source: https://github.com/wiz-lang/wiz/tree/master/examples/gb/sgb_snes_upload

- https://make.vg/get/homebrew/sgb_icd2_6003_test.gb - should say TEST PASSED if code upload works and writes to ICD2 register $6003 from the SNES are emulated. The GB detects multiple joypad mode can get enabled from a program that gets uploaded to SNES RAM, without doing a MLT_REQ. Passes on hardware. Currently fails on bsnes, higan, and bsnes-plus master.
- Source: https://github.com/wiz-lang/wiz/tree/master/examples/gb/sgb_icd2_6003_test

**Comment by devinacker** [comment]
Okay, 8b1b7bc should manage to fix how LCD buffering is handled (no more DMA hijacking...) Seems to work fine for the handful of games I tried.

As for your test ROMs, not sure what the deal is... I don't think DATA_TRN itself is broken, since Space Invaders still works fine, as does a test ROM that @qwertymodo made for adding MSU1 support to SGB games, which IIRC also uses DATA_TRN and JUMP packets in some fashion to get SNES-side code running alongside the GB game.

Do you know if any particular earlier revisions of the sgbdebug builds run your ROMs? I guess I should see if I caused an accidental regression somehow, I guess.

**Comment by devinacker** [comment]
Actually, one round of git-bisect later, it turns out that the same MLT_REQ fix that was discussed in #248 is to blame for the test ROMs not working.

Looking at how you're doing the SGB detection, I wonder if it's a timing issue involving the MLT_REQ packet... what happens if you delay for a frame or two after sending the MLT_REQ packet but before reading the input, to ensure that the SGB BIOS has time to write $6003?

**Comment by qwertymodo** [comment]
I was actually going to suggest looking at that one.  It broke some of my FFA SGB detection code when I upgraded, and I believe it was a timing issue due to mixing up two different versions of the SGBSDK, so I'd say definitely look into the timing.  Though, if it works on real hardware, then maybe that MLT_REQ change is buggy.

**Comment by devinacker** [comment]
It might just be because of the libgambatte core not being as tightly synced with the emulated SNES CPU as the other "built-in" components are. I'll experiment with it a bit and see what happens.
