### ISSUE TITLE
DSP Register Breakpoints

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#250]
Because of the way the SPC writes to the DSP registers via $F2 and $F3, it's possible to indirectly set breakpoints on DSP register writes, by setting the = comparison on F2 to the register you want to monitor, but you can't properly use the comparisons on the F3 value without a ton of extraneous breaks for writes to other registers.  It would be nice to add the DSP bus as a breakpoint source option.

**Comment by devinacker** [comment]
Was planning to do this at some point since I already added DSP registers as a memory editor source anyway, might as well knock it out.
