### ISSUE TITLE
Crash possibly caused by Break on WDM on SA-1 roms

### ISSUE THREAD

**Issue by lion65816** [devinacker/bsnes-plus#251]
Ran into this while programming a custom sprite.

I wanted to debug it utilizing the Break on WDM option but it kept crashing. I have inserted Vitor Vilela's SA-1 Pack beforehand and fellow SMWC users suggest that it could be from problems with SA-1 ROMs introduced in v05, as this has happened to others.

I've gone down a version to v04 at the suggestion of others and it works splendidly.
It is specifically the Break on WDM option as just having the WDM as is doesn't affect the program, as odd as that may seem. I did not test Break on BRK.

However I'm not sure if this is just a problem only affecting a few people, so sorry to be a bother.

**Comment by devinacker** [comment]
I'm not aware of any SA-1 related issues that were introduced in v05, but it's possible.

Could you attach an example ROM that causes it to happen?

Also, can you see if the issue also happens in [a recent development build?](https://ci.appveyor.com/project/devinacker/bsnes-plus/branch/master/artifacts)

**Comment by lion65816** [comment]
Sorry for taking so long to respond, I've been in the middle of other stuff and it kept slipping my mind. It still crashes.

[I've included a small SA1 patched file](https://github.com/lion65816/asm-shitpile/blob/master/smw.smc) with a custom sprite (my SMB3 burner, horizontal) with a WDM #$42 added at the start of its main code.

God speed!! o7

**Comment by lion65816** [comment]
The strange part is that it sometimes Did Work for me, though it depended on whether I was using too much memory or not. At one point it just started not working anyway. Shou ga nai I guess.

**Comment by devinacker** [comment]
Thanks, I'll try to check it out later today. Hopefully I can reproduce it and figure out what's going on.

**Comment by devinacker** [comment]
Should work now in the newest automated dev build, give it a try.
