### ISSUE TITLE
[bsnes-accuracy and performance issue] Full Throttle - textures tremble and flicker

### ISSUE THREAD

**Issue by Max833** [devinacker/bsnes-plus#256]
https://archive.is/LxuUv#selection-1463.78-1463.106

**Comment by devinacker** [comment]
Thanks for checking up on these issues. I meant to go through them all a while back but I guess they probably aren't available anymore outside of archived pages.

I'll take a look sometime soon.

**Comment by Max833** [comment]
Thank you and... you're welcome. Yes, they are all archived over here: https://archive.is/jd5qL

I think these four are most important issues.

**Comment by devinacker** [comment]
This is fixed in accuracy builds now, but currently not compatibility or performance since those both use the alternate CPU core.
