### ISSUE TITLE
firmware hash update

### ISSUE THREAD

**Issue by jjfmz42015** [devinacker/bsnes-plus#261]
The current documentation shows old hashes for the required files.

the current proper hashes for these are as follows.

Please update bsnes plus?

dsp1b.bin (SHA-256: D789CB3C36B05C0B23B6C6F23BE7AA37C6E78B6EE9CEAC8D2D2AA9D8C4D35FA9)
dsp2.bin (SHA-256: 03EF4EF26C9F701346708CB5D07847B5203CF1B0818BF2930ACD34510FFDD717)
dsp3.bin (SHA-256: 0971B08F396C32E61989D1067DDDF8E4B14649D548B2188F7C541B03D7C69E4E)
dsp4.bin (SHA-256: 752D03B2D74441E430B7F713001FA241F8BBCFC1A0D890ED4143F174DBE031DA)
st0010.bin (SHA-256: FA9BCED838FEDEA11C6F6ACE33D1878024BDD0D02CC9485899D0BDD4015EC24C)
st0011.bin (SHA-256: 8B2B3F3F3E6E29F4D21D8BC736B400BC988B7D2214EBEE15643F01C1FEE2F364)

**Comment by devinacker** [comment]
Those hashes are for the little-endian versions of the firmware files (normally with .rom extension), not the big-endian versions that bsnes-plus uses. (See https://www.caitsith2.com/snes/dsp/)
