### ISSUE TITLE
Unable to dump SPC while emulation is paused

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#263]
Steps to reproduce:

- Pause emulation by clicking "Break" in the debugger window (or by hitting a breakpoint)
- Open the SMP tab of the debugger window and note the current PC
- Click Tools>Capture SPC Dump in the main window

No SPC file is created

Now, click Run in the debugger window, and the SPC file will actually be created

However, if you view the SPC file in a hex editor, you can see that the dump actually occurred some time after the emulator resumed running, as the PC (stored at byte 0x25 in the file) is not the same as it was when the emulator was stopped, and when you actually took the dump.  This is not great if you're wanting to use the SPC file for reverse-engineering analysis, since you can't actually produce a dump at the point in time that you're intending to.

The same is also true for capturing screenshots, but that's probably less of an issue.

**Comment by devinacker** [comment]
Unlike the screenshot thing, this is actually intentional, so that SPC dumps don't get saved until the next time a note is triggered.

Do you think it'd make sense to have an option to just disable this behavior and save the dump immediately instead?

**Comment by qwertymodo** [comment]
Whether you make it an option or just change the behavior, it would be nice to have this functionality.  I've been working on a Ghidra loader for spc files, and it would be really helpful to be able to take spc dumps at precise timing (most common use case would be triggering an execute breakpoint on APU address $0000-FFBF in order to dump the state immediately after jumping to the initial code upload).

**Comment by KungFuFurby** [comment]
I'm interested in the dump immediately option myself because I find myself liking to make dumps just after the program initializes, but before it plays any music or any other commands... partially because in some cases, done correctly, I can just modify a single byte or two in the SPC700's CPUIO registers to play music and SFX on the fly in a single .spc file!

**Comment by charasyn** [comment]
Hello,
I have created an option that allows for immediate SPC dumping. Please see the PR that is linked.
Thanks,
Cooper
