### ISSUE TITLE
256kb BWRAM

### ISSUE THREAD

**Issue by spannerisms** [devinacker/bsnes-plus#269]
Currently, there seems to be some sort of %256 going on that prevents bsnes+ from creating 256kb .srm files. Setting $FFD8 to 7 works fine, giving 128k .srm, but writing 8 creates no .srm file and makes pages $40-$4F behave like open bus.

**Comment by devinacker** [comment]
The heuristics used for ROM headers only read the lowest 3 bits of the RAM size value (0-7), since that's what actual production cartridges were limited to. I suppose upstream bsnes does actually support using a value of 8, though. I'll backport that shortly.
