### ISSUE TITLE
Block move operations display incorrectly in debug window

### ISSUE THREAD

**Issue by mellonpizza** [devinacker/bsnes-plus#285]
mvn $bb, $aa is disassembled as mvn $aa, $aa, though otherwise it functions properly in terms of behavior.
![image](https://user-images.githubusercontent.com/22580852/115158494-64973a80-a05c-11eb-95d4-0650e8f06209.png)

**Comment by devinacker** [comment]
This is fixed in 37c4f6a already, feel free to grab a recent dev build: https://ci.appveyor.com/project/devinacker/bsnes-plus/branch/master/artifacts
