### ISSUE TITLE
AppVeyor artifact deletion policy

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#289]
AppVeyor has an artifact retention policy that deletes the build artifacts after 1 month.  Because there are often long gaps in activity on this repo, that often means that there are no AppVeyor builds available at all.  AppVeyor does have support for automatic deployment of builds, including the option of [deploying builds as GitHub releases](https://www.appveyor.com/docs/deployment/github/).  I think this is probably the best/easiest option here.  It would probably be good to set the pre-release flag for these CI builds, but otherwise I can't see any reason not to set that up, so that current builds are always available for download (along with older ones, in case of a regression).

**Comment by qwertymodo** [comment]
Something that is noted in the setup instructions, but probably worth emphasizing here, the process does require adding a GitHub OAuth token into appveyor.yml, but AppVeyor has the ability to encrypt that token, so be sure to do that before updating the YAML file in a public repo.

**Comment by devinacker** [comment]
Probably a good idea, though I really also need to get in gear and release an actual update so that people don't need to rely on dev builds so much.

I should also be able to automatically push builds to my own web space indefinitely, which would at least avoid clogging up the GitHub releases page.
