### ISSUE TITLE
Kidou Keisatsu Patlabor - font issue

### ISSUE THREAD

**Issue by Max833** [devinacker/bsnes-plus#297]
It does work with bsnes, but not with bsnes-plus (accuracy).

![image](https://user-images.githubusercontent.com/53529402/131257825-946356a3-936f-499f-8ef5-5b79c3fb6ab2.png)

**Comment by devinacker** [comment]
hm, this might be a pretty recent regression with high res mode not being rendered properly. I'll see what's up.

**Comment by devinacker** [comment]
Looks like the culprit is actually 0b636c1392755a66bd440f76268b8e699c202ddd, which was meant to fix a _different_ high res issue... argh.

**Comment by devinacker** [comment]
Should be good now.

Thanks for reporting this, I'm a bit embarrassed that high res mode was apparently broken in the accuracy PPU for over a year...

**Comment by Max833** [comment]
Your welcome! :) There are not _that_ many high res mode games. So... it makes sense. Thank you
