### ISSUE TITLE
Super Bases Loaded 3 - License to Steal (USA) "Backup was lost"

### ISSUE THREAD

**Issue by Max833** [devinacker/bsnes-plus#298]
I have noticed something that is a little bit strange. You get this screen when you start **Super Bases Loaded 3** for the first time (if you start it again it's gone) with bsnes, bsnes-plus and SNES9x, but not with Mesen-S

![image](https://user-images.githubusercontent.com/53529402/131313278-c18570f8-bbac-459e-a8d4-6e93fa21e2ab.png)

**Comment by devinacker** [comment]
This also happens on a real console when there's no pre-initialized SRAM. If it doesn't happen in Mesen-S, then that's a Mesen-S issue.
