### ISSUE TITLE
Savestate Crash

### ISSUE THREAD

**Issue by Yoshifanatic1** [devinacker/bsnes-plus#302]
BSNES Plus can sometimes crash without warning when attempting to save/load a savestate when the currently loaded game's .srm file is the incorrect size. I can get it to happen by adding at least 12 extra bytes to Donkey Kong Country 3's 2KB .srm file size, then attempting to savestate.

**Comment by devinacker** [comment]
I can't reproduce this. Which exact version of bsnes-plus are you using? Can you attach a .srm or savestate that causes it to happen reliably?

**Comment by Yoshifanatic1** [comment]
I'm using release version v05. And, yeah, I'll give you an .srm file. It's an otherwise normal .srm file for the USA version of DKC3 except that I added over 12 $00 bytes to the end of it.
[DKC3SaveFile.zip](https://github.com/devinacker/bsnes-plus/files/7465102/DKC3SaveFile.zip)

**Comment by devinacker** [comment]
How about with a [recent development build](https://ci.appveyor.com/project/devinacker/bsnes-plus/branch/master/artifacts)?

**Comment by Yoshifanatic1** [comment]
I tested it, and the crash doesn't happen in that build.

**Comment by devinacker** [comment]
This may have been inadvertently fixed at some point, then. Feel free to reopen this later if you still experience it with an up-to-date build.
