### ISSUE TITLE
bsnes-plus randomly turning on airplane mode 

### ISSUE THREAD

**Issue by hellocatfood** [devinacker/bsnes-plus#303]
I compiled bsnes plus on ubuntu 21.04 and after loading a cartridge bsnes-plus will suddenly turn on aeroplane mode after around 20 seconds. I've tried with multipled cartridges and can't see any error messages in the terminal about it.

**Comment by devinacker** [comment]
That is bizarre. Does this only happen after loading a cartridge? (i.e. not when leaving the emulator idle with nothing loaded)

**Comment by hellocatfood** [comment]
Yes, correct. It operates normally otherwise.

I can turn aeroplane mode off but if the game is still running it'll turn it back on again after 20ish seconds.

**Comment by devinacker** [comment]
Does dmesg show anything suspicious around the time when airplane mode gets deactivated?

Sorry for not paying much attention to this issue so far, I don't really have an up-to-date Ubuntu VM handy at the moment.

**Comment by hellocatfood** [comment]
The only message from `dmesg` is

`[22638.926440] wlp2s0: deauthenticating from c0:a3:6e:4f:43:ed by local choice (Reason: 3=DEAUTH_LEAVING)`

**Comment by hellocatfood** [comment]
The only message from `dmesg` is

`[22638.926440] wlp2s0: deauthenticating from [mac address] by local choice (Reason: 3=DEAUTH_LEAVING)`

(I removed my mac address)

**Comment by devinacker** [comment]
What happens if you comment out the call to `supressScreenSaver()` [here](bsnes/ui-qt/application/application.cpp#L240) and rebuild? I wonder if the way that's implemented on Linux is just causing something strange to happen with power management.

**Comment by hellocatfood** [comment]
It worked! Been playing DK Country for 5 minutes and airplane mode hasn't been switched on. Thanks for addressing it

**Comment by TheKodeToad** [comment]
I realise this is old, but this is still an issue.
It seems pressing keycode 255 activates airplane mode. Maybe another key should be used.
Running xdotool keydown 255 also has this behaviour.
