### ISSUE TITLE
WDM under sa-1 crashes the emulator

### ISSUE THREAD

**Issue by GhbSmwc** [devinacker/bsnes-plus#310]
SMW romhacker here. I experienced a crashing bug during working on my [HUD element documentation](https://github.com/GhbSmwc/SMW_StatusBarTutorial) that the custom sprite (having a WDM to breakpoint to) causes the emulator to close out when you enable breakpointing on WDM. It is important to note that this code runs under SA-1, not the main CPU.

To reproduce this bug, do these in the order written:

SA1:
Have the SMW game, expand the ROM using [LM](https://www.smwcentral.net/?p=section&a=details&id=28429) without any other edits, patch using [asar](https://www.smwcentral.net/?p=section&a=details&id=25953) of [this patch](https://www.smwcentral.net/?p=section&a=details&id=25938)

Shared subroutines:
Insert the [shared subroutines patch](https://www.smwcentral.net/?p=section&a=details&id=19545) (as the sprite needs it), follow the instructions there. Also don't forget that the folder `SharedSub_Defines` also need to be copied and pasted in later step

Custom sprites:
Paste `SharedSub_Defines` folder in the same location as pixi.exe (not inside any of the other folders)
After SA-1'ing the game, use [pixi](https://www.smwcentral.net/?p=section&a=details&id=26026) to insert the sprite [found here](https://github.com/GhbSmwc/SMW_StatusBarTutorial/tree/master/Pixi_CustomSprite), edit that so that it has the WDM under the `SpriteCode` label:
```
SpriteCode:
	PHB : PHK : PLB
	WDM
	LDA $9D
```

and have the list.txt of sprites you want to insert into the game:
```
01 TestSprite_RepeatedIcons.json
```
Make sure that list file is at the same location as the game itself. Now run pixi.exe and follow the prompts there (command prompt-like console window, it accepts file paths).

Back on LM:
In any level (preferably level 105, the default level when starting LM), hit INSERT while in sprite editing mode (the green koopa shell icon is pressed on the toolbar at the top), command should be `0` and the extra bits set to `3`.

Bsnes+ running:
Start the game, open the debugger, on breakpoint, enable `break on WDM`, now enter the level containing the sprite (left from yoshi's house). When the level finished loading, the emulator freezes and crashes.

**Comment by devinacker** [comment]
This should be fixed in 5408c5b66f4f8c92f0293619a02a2818cac44ed4 already. Have you tested this in a recent development build?

**Comment by GhbSmwc** [comment]
This was tested on August 18, 2019 version 5. Should've updated the program from time to time.

**Comment by devinacker** [comment]
Appveyor has the most recent dev build available for about 1 more week: https://ci.appveyor.com/project/devinacker/bsnes-plus/branch/master/artifacts

(I'm going to work on a more permanent solution for hosting these, but for now, give this one a try)
