### ISSUE TITLE
Holy Umbrella petrified npc bug

### ISSUE THREAD

**Issue by CharlesCorrin** [devinacker/bsnes-plus#316]
In Holy Umbrella, you get to a village known as Surelulla Village in the translation patch by Aeon Genesis. In short time, the village's people are all petrified by a villain. When you try talking to them, it tells you they're petrified. But then the bug occurs. The petrified npcs will start walking in place while still petrified. Their sprites will also often change to a random different npc sprite. I don't know how it determines what they change into.

I thought this might only occur in the fan translation. But when I tried it without the translation applied, it still happened. I thought the problem might somehow be in the "normal" bsnes core, so I tried it in the accuracy core. It happens there too.

It's possible this bug happens on the real console. I can't test it. But it seems like a very strange bug to leave in the game if so!

My system: Windows 10 64-bit, latest version as of this writing.

The emulator: bsnes-plus 5.92-master downloaded from appveyor. Confirmed to occur in both regular core and accuracy core.

The game: Holy Umbrella - Dondera no Mubou!! (Japan)

CRC-32: F0A9DEAD
MD-5: 69D50AA193E7B3988C761F96C5DCDD5A
SHA-1: D3A26291AEDCBBC4725165DD4EFF569236086AC0

I included 4 different save states and a save file. If you want to use the save file, you'll need to exit the building, then the town through the bottom to get to the world map. Then go to the area just to the right of the village you exited.

If you want to see the bug in action, it appears at the 16:28 mark in this video:
https://www.youtube.com/watch?v=3S_RihDMN_Y

Other videos on Youtube also show the bug.

I'm very interested in seeing how this turns out.
[Saves.zip](https://github.com/devinacker/bsnes-plus/files/7833602/Saves.zip)

**Comment by devinacker** [comment]
This definitely sounds like a game bug to me, especially if it appears in videos that were probably recorded using other emulators. I can test your save file on my console later just to be sure, though.

**Comment by devinacker** [comment]
Can confirm that this happens on original hardware using the Japanese ROM.
