### ISSUE TITLE
Super Gameboy not working

### ISSUE THREAD

**Issue by internet-police** [devinacker/bsnes-plus#317]
When i try to load a gameboy rom, i only see the frame of the Super Gameboy, but the game will not load
I tried to open the .gb rom directly or load the supergameboy.rom first
am i doing it wrong?
(original bsnes will open a new file selector dialog when i start the supergameboy.rom)

**Comment by devinacker** [comment]
Use the `System > Load Special > Load Super Game Boy Cartridge` option to load the SGB ROM and the game at the same time.
