### ISSUE TITLE
Can't keep Debugger window closed when at a breakpoint

### ISSUE THREAD

**Issue by jeffythedragonslayer** [devinacker/bsnes-plus#319]
Steps to recreate:

	1. Clone Pino's LoRom template
	2. Put a WDM 0 somewhere in the game loop
	3. Build the LoROM template
	4. Open lorom-template.sfc in bsnes+
	5. Goto Tools->Debugger
	6. Goto Tools (in the debugger)->Breakpoint Editor
	7. Check "Break on WDM"
	8. Attempt to close Debugger by clicking the X

The Debugger window flashes away and comes back again.  I was expecting the emulation to remain paused at the breakpoint.  (Or perhaps it is supposed to resume the CPU when closing the debugger?)

**Comment by devinacker** [comment]
This is intentional behavior. I don't think it'd be particularly useful or intuitive to allow the debugger to keep emulation paused when it's not visible.

**Comment by jeffythedragonslayer** [comment]
Oh, ok.
