### ISSUE TITLE
happy face not appearing in Tile Viewer

### ISSUE THREAD

**Issue by jeffythedragonslayer** [devinacker/bsnes-plus#324]
The happy face in bazz's vram2.smc (found in the 7z at the bottom of https://wiki.superfamicom.org/working-with-vram-part-2-initializing-tiles-and-tile-maps) appears totally black in bsnes-plus' Tile Viewer (v05.92-master):

![image](https://user-images.githubusercontent.com/13253146/175197695-50f2f7c2-5a08-463b-998a-6745d8ef78f9.png)

It appears fine in Mesen-SX:

![image](https://user-images.githubusercontent.com/13253146/175197606-7ed4e57f-aed9-4616-aaa9-58bed98b22a4.png)

**Comment by devinacker** [comment]
The graphics are 2bpp, not 4bpp.

![image](https://user-images.githubusercontent.com/4616298/175198184-33f14a85-4681-45bb-8c1e-30392a6d3ed1.png)
