### ISSUE TITLE
Auto detect bit depth

### ISSUE THREAD

**Issue by jeffythedragonslayer** [devinacker/bsnes-plus#325]
Can the Tile Viewer auto-detect the bit depth so confusion like https://github.com/devinacker/bsnes-plus/issues/324 doesn't happen?

**Comment by devinacker** [comment]
If you click one of the "goto" buttons near Base Tile Addresses, it'll automatically set both the address and bit depth for that particular layer. Otherwise, there's really nothing to "detect" since the SNES almost always has graphics of multiple bit depths on screen at the same time.

**Comment by jeffythedragonslayer** [comment]
Good tip, thanks.
