### ISSUE TITLE
[Ubuntu] Airplane mode gets turned on when debugger screen is opened

### ISSUE THREAD

**Issue by dezoitodemaio** [devinacker/bsnes-plus#344]
Whenever i open the Debugger window, my laptop starts to behave weirdly. The airplane mode keeps turning on and when i turn it off, it turns on again, and again. If i close the Debugger window, it stops.

My config:

Ubuntu 20.04.5 LTS
bsnes-plus built from source, commit [3a2a2ed](https://github.com/devinacker/bsnes-plus/commit/3a2a2ed2f859f09c2234e7549ef3e3717519e5a1)

**Comment by devinacker** [comment]
https://github.com/devinacker/bsnes-plus/issues/303#issuecomment-962469833 This comment has a potential workaround, though I still need to implement an actual fix at some point.

**Comment by dezoitodemaio** [comment]
commenting out supressScreenSaver() solved it.
