### ISSUE TITLE
Save state loading (F4) sometimes make the emulator crash

### ISSUE THREAD

**Issue by SigmaVirus** [devinacker/bsnes-plus#42]
@devinacker 

First off, let me just say thanks for this fork of bsnes v073 because it has working mbc2 which makes it possible to save/load properly in Kid Icarus - Of Myths and Monsters something that the vanilla build and the King of Chaos build of v073 didn't have.

Now to business, every now and then when you try to load a save state the emulator crashes and I'm forced to close and reload it.
This does not happen on said builds mentioned above just in bsnes-plus and it's very random, sometimes I can spam F4 and it loads the state just fine and other times it's just crashing.

I only use this fork for Super Game Boy purposes mainly because it's a hell of a lot easier to use then newer higan versions and that it's still use Gambatte for GB making it the best solution for Super Game Boy really.

**Comment by devinacker** [comment]
I'll check it out, can you send me an example of a savestate that you know is able to cause the crash? (I wonder if it's specifically related to SGB games or something...)

**Comment by SigmaVirus** [comment]
Thanks for your answer @devinacker!

It happens with any game and any save state you make really (at least for me as I don't own many Game Boy games), and it's so random that you never know if loading will work for a sustained amount of time or crash right away.

I don't know if it's SGB related or not because I only use these bsnes iterations for SGB.
I use the Libretro bsnes accuracy core in RetroArch for Super Famicom games.

However what I do know is that these crashes is also present in @awjackson bsnes-classic too so I don't know how far back this issue goes or what they have in common.

Could be I have been lucky all this time in the vanilla and King of Chaos build of bsnes v073 and never triggered a crash.

**Comment by devinacker** [comment]
Still haven't been able to reproduce this with SGB games, though I haven't done a lot of in-depth investigating. Could somehow be a mapper-specific issue or something.

I do plan on updating libgambatte before the next release, just in case that fixes the issue somehow.

**Comment by SigmaVirus** [comment]
I haven't been able to try anymore of this out since I started a new job recently.

There's no rush on this and besides it only crashes when save stating, I could just stop using save states all together but I have been spoiled with using them for so bloody long.

**Comment by SigmaVirus** [comment]
@devinacker 
I'm closing this since I can't reproduce it anymore.
