### ISSUE TITLE
Run/Step buttons should transfer focus to main window

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#45]
In order to play nice with the "Pause emulation when main window does not have focus" option, which is useful when switching between all of the various debugger windows, the Run and Step buttons should trigger a focus change when clicked to switch to the main window.  Otherwise, single stepping requires you to click step, then click into the main window, click step, click main window, back and forth.

**Comment by devinacker** [comment]
I was planning on eventually having the main debug window take focus when hitting a breakpoint / finishing a step / etc, so this can probably be done at the same time. Should be taken care of soon-ish.

**Comment by devinacker** [comment]
okay, resuming emulation with the Run button now always switches back to the main window, and the step buttons do the same if required by the focus policy. The debug window also becomes active between steps or when a breakpoint is hit.
