### ISSUE TITLE
S-CPU registers values not showing up in Memory editor

### ISSUE THREAD

**Issue by ddfst** [devinacker/bsnes-plus#46]
The whole 4200-431F area is filled with zeros.
Is there any way to see the correct value of, for example, $4212 while step-by-step debugging?

**Comment by devinacker** [comment]
Currently, memory-mapped registers aren't displayed in the memory viewer to avoid any side-effects that happen when reading the registers. Some (but not all) relevant info can be seen using the properties viewer in the debugger's Tools menu.

At some point I'll probably either make the registers readable without side effects or else just increase the amount of state information that's shown in the properties window.
