### ISSUE TITLE
Minor typo in accuracy profile build

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#48]
bsnes/snes/ppu/mmio/mmio.cpp:722:33: error: expected ')' before '{' token
    if(!Memory::debugger_access() {

Simple case of a missing close paren, breaks accuracy profile build.

**Comment by devinacker** [comment]
This had been fixed in ed1a89e09feef4cc0a72e301df5ad314d4b38eba which I had apparently forgotten to push. Thanks for the notice.
