### ISSUE TITLE
Keep last frame visible when pausing emulation

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#49]
Currently, when emulation is paused, such as when the main windows looses focus, the screen gets blanked.  It would be nice if the last frame rendered was displayed instead.  Otherwise, it makes it difficult to debug issues where you want to step through to a specific frame, because you can't see which frame you're on when stepping.

**Comment by devinacker** [comment]
should be fixed by 33cf22f, give it a try

**Comment by qwertymodo** [comment]
Works great, thanks :)
