### ISSUE TITLE
Add widescreen option? 

### ISSUE THREAD

**Issue by jvhellraiser** [devinacker/bsnes-plus#50]
I hate seeing the emulator in a wide screen monitor as something square in the middle of the screen
is kinda looks weird and annoying. at least if i can stretch it make a wide screen option.

**Comment by devinacker** [comment]
Probably not going to happen, simply because the SNES itself is not designed for widescreen, and I personally really don't like stretching non-widescreen images out to 16:9 or 16:10.

**Comment by devinacker** [comment]
A little late, but I wanted to correct myself - there are two widescreen modes in Settings > Video Mode that are only available when in fullscreen mode.
