### ISSUE TITLE
Save states do not save/restore MSU-1 status

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#54]
Loading a save state in a MSU-1 enabled game doesn't properly reload the MSU-1 state.  Symptoms vary by game, but mostly it means you load your game with no background music playing.

**Comment by devinacker** [comment]
I assume higan works as expected, at least?

There's also a MSU-1 feature I've been meaning to finally backport - namely, the audio resume support that was added to the spec a few higan versions ago, so I'll probably tackle both of those things at the same time.

**Comment by qwertymodo** [comment]
Yes, higan works correctly.  If you save a state and then load it, the MSU-1 audio gets reloaded along with everything else.

**Comment by devinacker** [comment]
audio_busy, audio_repeat, and audio_play are all cleared when writing to $2005. The busy flag probably doesn't matter since it's nearly always false anyway (and in higan it *is* always false, unless I'm missing something).
