### ISSUE TITLE
VRAM viewer improvements

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#62]
I find myself switching to NO$SNS a lot when trying to debug VRAM contents, due to the fact that its VRAM viewer has a lot of nice features missing from bsnes-plus.  Unfortunately, NO$SNS doesn't seem to support the MSU-1, so debugging MSU-1 video got to be quite frustrating at times.  I don't know if you've used it or not, but here's the different views available.

Starting with just the current screen, kind of redundant, but I'll show it here so you can see what image is being referenced in the other screens.

![nocash_vram](https://cloud.githubusercontent.com/assets/5988870/19500532/0943af24-9553-11e6-8a68-1a6588d65ee4.png)

Next, it displays each BG layer separately, so you can see what parts of the image are located on which BG layer
![nocash_bg1](https://cloud.githubusercontent.com/assets/5988870/19500543/23db25c4-9553-11e6-9fce-95ff456156c9.png)
![nocash_bg2](https://cloud.githubusercontent.com/assets/5988870/19500545/279cde1e-9553-11e6-822b-43744429a0df.png)

Mousing over any pixel in the image will populate the dialogs on the right, telling you about the tile, and displaying that tile in the top-right.

![nocash_4bpp](https://cloud.githubusercontent.com/assets/5988870/19500669/3e2a03b8-9554-11e6-85b3-c0bc003c9e1f.png)

The 2bpp/4bpp/8bpp tabs break up the display into individual tiles, so you can see where the tile boundaries are.  Again, mousing over displays data on the right-hand side.  In 8bpp mode, it even displays the tiles in color based on the current CGRAM contents.  It should be possible to display colors in 2bpp and 4bpp modes as well, using the tilemap for palette selection, but obviously it's possible for a single tile to be reused with multiple palettes, but even if you just picked one, it would still be nice to see the tiles displayed with some kind of color.  That aside, and perhaps most importantly, the tiles are scaled up considerably to the point that you can actually view them, unlike bsnes-plus' current VRAM viewer where you'd need a microscope to see individual pixels.  And the blown-up mouseover view in the top-right helps in that regard as well.

Finally, the OAM viewer:
![nocash_oam](https://cloud.githubusercontent.com/assets/5988870/19500629/c2305802-9553-11e6-9e17-a2735797a529.png)
Mousing over a sprite not only updates the data on the right-hand side, it also highlights that sprite on the screen.

**Comment by devinacker** [comment]
Having more features for viewing tilemaps and stuff is a thing I've wanted to add for a while now, and it's probably the main thing I'm going to focus on once I start working on the project more actively again.

**Comment by undisbeliever** [comment]
I'm in the mood to work on this. I seriously need a better VRAM viewer to help in future engine debugging.

I'm aiming to:
 * change the width of the tilemap to 16 tiles (to match the real SNES)
 * add zoom
 * add palette selection in tilemap
 * display tilemap/char vram address in the window to make searching easier

**Comment by undisbeliever** [comment]
Here is what I've done so far, what do you guys think?

![screenshot](https://cloud.githubusercontent.com/assets/65687/19606218/3e01240e-9804-11e6-9c94-cdaee6a1a525.png)
https://github.com/undisbeliever/bsnes-plus/tree/update-debugger

I still need to test this in Windows to confirm nothing's broken.

**Comment by devinacker** [comment]
Looks good! I'll try to build it in Windows and play with it later today.

**Comment by undisbeliever** [comment]
Can now select the VramViewer palette from CGRAM

https://github.com/undisbeliever/bsnes-plus/tree/update-debugger
![screenshot](https://cloud.githubusercontent.com/assets/65687/19626177/7e1ecc1a-996e-11e6-8155-4cf95f77f33a.png)

**Comment by qwertymodo** [comment]
Just got a chance to try it out, and it is a HUGE improvement over the old viewer.  THANK YOU.  I hope you might also consider some of the other view options I posted, such as the individual BG views where it shows the actual screen contents using the tilemaps for each BG, or the OAM viewer.

Also, an adjustable width on the tile viewer would be nice:

![vram_viewer](https://cloud.githubusercontent.com/assets/5988870/19902467/1bf8c71e-a028-11e6-85fe-a9dedad50ee2.png)

**Comment by devinacker** [comment]
I do plan to add background map viewers and other stuff like that soon as well. 

Right now I'm thinking I will probably publish a new official release _before_ that happens, just because it's been a while since the last one and I'd like to get the recent improvements officially packaged up. More VRAM tools are definitely on the way, though.

**Comment by devinacker** [comment]
Alright, I feel like @undisbeliever's latest updates for the new version have most of the stuff discussed here pretty well covered... I feel like maybe the OAM/sprite viewer could probably still use some sprucing up but that might be for another time. Gonna go ahead and (finally!) close this one.
