### ISSUE TITLE
Compiling 64-bit Windows binaries

### ISSUE THREAD

**Issue by BooBerry** [devinacker/bsnes-plus#68]
Greetings!

I've been trying to compile a 64-bit binary of the accuracy profile on Windows 10 Anniversary Update 64-bit without any success. I'm using MingGW-w64 (from the Sourceforge site - specifically I'm using **x86_64-4.8.2-release-posix-seh-rt_v3-rev3** as this matches the version supported by Qt 4.8.6). For Qt I'm using **qt-opensource-windows-x86-mingw482-4.8.6-1** - both MingGW-w64 and Qt are added to my PATH correctly (which are C:\mingw64\bin and C:\Qt\4.8.6\bin in this case). Of course, I'm assuming this is the correct version of Qt as the readme instructions are pretty vague on which Qt file(s) to use.

These are the errors I'm encountering during compiling (compiling goes nearly all the way, until the end where it ultimately fails):

_ACCURACY -DDEBUGGER -c snes/chip/serial/serial.cpp -o obj/snes-serial.o
g++ -std=gnu++0x -o out/bsnes obj/ui-main.o obj/ui-base.o obj/ui-cartridge.o obj/ui-debugger.o obj/ui-input.o obj/ui-movie.o obj/ui-settings.o obj/ui-state.o obj/ui-tools.o obj/ruby.o obj/resource.o obj/libco.o obj/snes-system.o obj/snes-cartridge.o obj/snes-cheat.o obj/snes-memory.o obj/snes-cpucore.o obj/snes-smpcore.o obj/snes-cpu.o obj/snes-smp.o obj/snes-dsp.o obj/snes-ppu.o obj/snes-supergameboy.o obj/snes-superfx.o obj/snes-sa1.o obj/snes-necdsp.o obj/snes-bsx.o obj/snes-srtc.o obj/snes-sdd1.o obj/snes-spc7110.o obj/snes-cx4.o obj/snes-obc1.o obj/snes-st0018.o obj/snes-msu1.o obj/snes-serial.o -s -mwindows -mthreads -luuid -lkernel32 -luser32 -lgdi32 -lcomctl32 -lcomdlg32 -lshell32 -lole32 -Wl,-enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-reloc -LC:/Qt/4.8.6/lib -LC:/Qt/4.8.6/plugins/imageformats -lQtCore4 -lQtGui4 -lmingw32 -lqtmain -lcomdlg32 -loleaut32 -limm32 -lwinmm -lwinspool -lmsimg32 -lole32 -ladvapi32 -lws2_32 -luuid -lgdi32 -lQtCore4 -lQtGui4 -ld3d9 -lddraw -lopengl32 -ldsound -ldinput8 -ldxguid -ldinput8 -ldxguid
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtCore4.a when searching for -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib\libQtCore4.a when searching for -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtCore4.a when searching for -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtGui4.a when searching for -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib\libQtGui4.a when searching for -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtGui4.a when searching for -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libqtmain.a when searching for -lqtmain
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib\libqtmain.a when searching for -lqtmain
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libqtmain.a when searching for -lqtmain
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtCore4.a when searching for -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib\libQtCore4.a when searching for -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtCore4.a when searching for -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQtCore4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtGui4.a when searching for -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib\libQtGui4.a when searching for -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Qt/4.8.6/lib/libQtGui4.a when searching for -lQtGui4
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQtGui4
collect2.exe: error: ld returned 1 exit status
Makefile:86: recipe for target 'build' failed
mingw32-make: **\* [build] Error 1
Press any key to continue . . .

Just for the fun of it, I setup a 32-bit build (using **i686-4.8.2-release-posix-dwarf-rt_v3-rev3** of MinGW-w64) and replacing C:\mingw64\bin with C:\mingw32\bin in my PATH and compiling again... it worked fine.

I believe the problem is with Qt... and I believe it's x86 only. I looked all over Qt's site for a x64 Qt 4.8.6 and I couldn't find one.

So here's my question and comments:

1) What do I need to compile a 64-bit binary on Windows?

2) In my opinion the readme instructions for building on Windows needs updated for both 32-bit and 64-bit architecture building. They're too vague and can lead to issues like this.

3) Specifically the readme needs to specify specific files recommended to compile 32-bit and 64-bit binaries on Windows (e.g. **i686-4.8.2-release-posix-dwarf-rt_v3-rev3.7z** for MinGW-w64 32-bit and **x86_64-4.8.2-release-posix-seh-rt_v3-rev3.7z** for MinGW-w64 64-bit and **qt-opensource-windows-x86-mingw482-4.8.6-1.exe** for Qt 4.8.6 32-bit, etc.).

Thank you. :)

**Comment by devinacker** [comment]
You're correct, building a 64-bit build of the emulator requires 64-bit Qt binaries, which Qt itself doesn't provide for Windows for some reason. I'll have to find the sourceforge repo with the binaries I currently use. The Windows build instructions date back to before I started providing/supporting 64-bit builds.

As for specific compiler releases, I'd rather leave most of that to the user's discretion, since they may already have a usable toolchain installed, or there may be a more up-to-date one available than there was at the time of writing, etc. The main point of importance is installing a version of Qt 4 that matches their compiler configuration, as well as other suggestions like choosing SEH over SJLJ for performance reasons, etc.

**Comment by BooBerry** [comment]
Fortunately, I found qt-4.8.6-x64-mingw492r1-seh on the Qt64-NG Sourceforge page. It works! Got a working Windows 64-bit accuracy binary. :D

**Comment by devinacker** [comment]
closing for now since 64-bit Qt5 binaries are now included as part of the project (when using the official build method via mingw-w64 or msys2)
