### ISSUE TITLE
SMP Breakpoint Bug

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#71]
Sometimes, SMP breakpoints are not working as expected.  For instance:

Addr[08D]-[090] Data[] R[x] W[] X[] Source[S-SMP bus]

triggered on

..08de mov   $08f,a           A:00 X:00 Y:00 SP:01fd YA:0000 nvpbhiZc
and
..08e3 mov   $090,a           A:ff X:00 Y:00 SP:01fd YA:00ff Nvpbhizc

both of which are *writes* to the specified addresses, not reads.

**Comment by qwertymodo** [comment]
So far in my testing, write breakpoints seem to work correctly (at least as far as I can tell, it could be missing some and I wouldn't know), the only issues I've noticed are with the reads.

**Comment by devinacker** [comment]
For whatever reason, most write instructions on the SMP will first do a dummy read from the destination address before performing the write. I assume this is what's actually supposed to happen (higan does it too), but it's the reason for the breakpoints you're getting.

I'll probably have to come up with a way to prevent those dummy reads from actually triggering breakpoints.

**Comment by qwertymodo** [comment]
The unfortunate thing, though, is that it's not triggering on any actual reads from those same locations (though, it's possible that those locations are never read from after they're written, but it's unlikely given their purpose, as far as I can tell from the code I've disassembled so far).

**Comment by devinacker** [comment]
If you put execution breakpoints on instructions that read those addresses, do they get triggered?

**Comment by devinacker** [comment]
Got it.
