### ISSUE TITLE
Nothing visible in Sprite Viewer

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#77]
Is the box in the upper-right corner of the sprite viewer supposed to actually display the sprite?  Because all I get is solid black, no matter which sprite I click on.
![bsnes-plus_sprite_viewer](https://cloud.githubusercontent.com/assets/5988870/20240917/09542e22-a8da-11e6-95b5-6cff51f6b8b3.png)

**Comment by devinacker** [comment]
Well, it's _supposed_ to, but... apparently it allocates an image to put there but then never actually renders anything to it.

Shows you how little I've actually used that window if I managed to never notice...

I'll probably end up refactoring some code from the new VRAM viewer to make this work.

**Comment by devinacker** [comment]
Also, the "size" column currently ignores the actual OAM base size setting, so it'll only ever show a width/height of 8 or 16. I'm probably going to add a bit to the PPU debugger(s) in order to handle this well.

**Comment by undisbeliever** [comment]
> Shows you how little I've actually used that window if I managed to never notice...
Same Here.

I'll work on this tonight.

**Comment by devinacker** [comment]
@undisbeliever thanks!

I suggest moving some drawing code (and possibly palette generation code) out of VramCanvas so that it can be reused by the OAM viewer and (eventually) a tilemap viewer as well. Doesn't need to be a major refactor, just something to allow all of those things to use the same code to render a single 8x8 tile with the right palette colors.

**Comment by undisbeliever** [comment]
> I suggest moving some drawing code (and possibly palette generation code) out of VramCanvas so that it can be reused by the OAM viewer...

That's defiantly something we are going to have to work on. I just wrote a new tile drawing function so it could handle tile wrapping. Tile flipping is not preformed by the drawing code, but instead by the scaling code.

---
Sprite Viewer is completed: https://github.com/undisbeliever/bsnes-plus/tree/update-debugger

Notable thoughts:
 * Tile scaling is determined by oam_base_size. I personally find the way that no$sns' debugger handles OAM tile scaling to be annoying, so I decided to have the small and large tiles to use the same pixel size.
 * User can sort the columns. This should make searching the OAM easier.
 * Moved the name table bit into Char column.
 * Increased column spacing.

![screenshot](https://cloud.githubusercontent.com/assets/65687/20286065/bfb0366a-ab10-11e6-8c51-1ec5bbc8087c.png)

As usual this will need to be tested on OSX and Windows by someone other than me.

**Comment by qwertymodo** [comment]
Looks good to me.

**Comment by devinacker** [comment]
Works great. Thank you!

**Comment by qwertymodo** [comment]
I just want to say thank you both a ton for your work on this.  Having a decent, working, *accurate* debugging emulator makes life so much nicer, and having it actively developed to keep adding useful features so I don't have to keep switching between 3 different emulators, each with their own bugs, just so I can get one or two features from each, has been hugely helpful.  It's easy to take your tools for granted until you actually get the chance to use good ones :)
