### ISSUE TITLE
Jerky screen

### ISSUE THREAD

**Issue by Cibomatto2002** [devinacker/bsnes-plus#84]
Sometimes the screen will be jerky the only why I can fix it is to go out of full screen play a little bit then go back to full screen. 

Operating System
	Windows 10 Home 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co., Ltd. H81

**Comment by devinacker** [comment]
Sounds like a vsync issue; do you have "synchronize video" enabled? (Settings > Emulation Speed)

Also, try using a different renderer (settings > config > advanced) if you haven't already.

**Comment by Cibomatto2002** [comment]
That fixed it but now I got a new problem I loose frames it will drop to 54 FPS to 59 sometimes like every 15 seconds or so.  the CPU runs at 56% I have Video and Audio sync on at the same time. 
![capture11-27-2016-12 04 36 am](https://cloud.githubusercontent.com/assets/21169038/20645975/489f4df8-b435-11e6-85da-2834ce71d843.jpg)
