### ISSUE TITLE
Porky Pig's Haunted Holiday (USA)

### ISSUE THREAD

**Issue by Cibomatto2002** [devinacker/bsnes-plus#87]
As you can see there is a black bar on the right I"M not sure if that's a big in the emulator or that's the way the game is.

![capture11-24-2016-5 21 18 pm](https://cloud.githubusercontent.com/assets/21169038/20611196/4d80b8c8-b26b-11e6-9dae-943d3e2d5d44.jpg)

**Comment by devinacker** [comment]
This is the correct behavior; the game masks out the rightmost 8 pixels of the screen for some reason (maybe to avoid scrolling artifacts).
