### ISSUE TITLE
Directdraw or OpenGL Video Filters don't work in full screen

### ISSUE THREAD

**Issue by Cibomatto2002** [devinacker/bsnes-plus#88]
I can't get any of the Video Filters to work in Directdraw or OpenGL in full screen.

**Comment by undisbeliever** [comment]
bsnes uses separate filter settings for full-screen and windowed mode.

In full-screen mode, press tab to engage the menu, then select the video filter to use.

**Comment by Cibomatto2002** [comment]
Thank you.
