### ISSUE TITLE
SA-1 Tracing Crash

### ISSUE THREAD

**Issue by danielburgess** [devinacker/bsnes-plus#91]
To reproduce the issue, load the Marvelous - Another Treasure Island ROM. Start the debugger and enable "Trace SA-1 opcodes" then enable trace mask (doesn't really need to be enabled for the crash to happen). Start a new game. Once the game starts to load, the emulator will crash.

This crash happens with every bsnes-plus version (tested on windows and a couple different machines).

Here is one of the trace logs that I got most recently- not sure which version this was output from.
[trace.log.txt](https://github.com/devinacker/bsnes-plus/files/647673/trace.log.txt)

**Comment by devinacker** [comment]
Well, now I feel a little dumb - this was a simple case of me doing a sloppy copy/paste two years ago which caused the trace mask buffers for SA1 and SuperFX to be undersized and somehow nobody noticed.

**Comment by danielburgess** [comment]
No need to feel dumb. Strangely enough, I've been able to trace some SA-1 opcodes, but not most others. I would have reported it sooner, but I assumed it was me until I tried on a different computer a few weeks ago and experienced the same problem. Thanks for fixing it so quickly!
