### ISSUE TITLE
Weird MSU-1 issue.

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#93]
I can't really figure out what is causing this, so I'll just list steps to reproduce.

-Download DarkShock's Mega Man X MSU-1 patch: http://www.romhacking.net/hacks/2274/
-Patch/download audio/etc
-Run the game
-Select Pass Word at the main menu
-MSU-1 audio stops working, even after a reset/reload

Setting a breakpoint at $80FBD0 (the MSU-1 audio routine) and stepping through shows that reading $2002, which should return #$53, instead returns #$20.  This doesn't happen in Snes9x or higan v101, so it's not an issue with the game itself.

**Comment by qwertymodo** [comment]
Nevermind, PEBKAC.  Really weird, but it's definitely an issue on my end.

**Comment by devinacker** [comment]
Out of curiosity, what was the actual issue?

**Comment by qwertymodo** [comment]
Not 100% sure, but I think I screwed up the manifest, and fooled myself into thinking that the title screen was actually playing the MSU-1 audio.  So it just wasn't playing at all, but it's working now.
