### ISSUE TITLE
Trace log broken?

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#94]
When I enable trace logging for CPU opcodes, it only seems to log about 200 lines and then just... quits.  The game continues running at full speed, where normally it would grind to a crawl during logging, and no matter what I do, it only logs those few lines.  Sometimes it's as few as 20.  I can't find any pattern to it, other than the fact that it always seems to quit after a full line, it's not cutting out in the middle of a line.  I don't recall seeing this issue on any of my git builds before v3, this is new on the v3 release, so it has to be fairly recent.

**Comment by devinacker** [comment]
Try applying 8cead80154f7557e50864b9b6a546b3ee9971faa. It looks like an earlier commit mistakenly caused the trace mask to sometimes be enabled when it shouldn't have been.

**Comment by qwertymodo** [comment]
I don't have my build environment available at the moment (Qt is such a bear of a dependency... no wonder byuu ditched it), but I'll try it when I get the chance.  One thing I've been wondering, what exactly **is** the trace mask, and how does it work (assuming it's behaving correctly)?

**Comment by devinacker** [comment]
The trace mask causes each instruction to only be logged the first time it's execued. It's probably the reason you'd see logging appearing to stop at unpredictable times.
