### ISSUE TITLE
Mirror cheats between Fast/SlowROM banks

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#97]
Cheats which modify ROM addresses should be mirrored to affect both FastROM and SlowROM.

e.g. 07cb9aea should also mirror as 87cb9aea

**Comment by undisbeliever** [comment]
I don't think we should do this, it will break the few games that use ExLoROM or ExHiROM memory maps.

**Comment by devinacker** [comment]
I've been meaning to fix this for quite a while now (see the last bullet under "coming soon" in README.md). Wouldn't really be any more difficult than supporting mirrored addresses with breakpoints, which is already supported.

>I don't think we should do this, it will break the few games that use ExLoROM or ExHiROM memory maps.

No it won't; just like with single breakpoints, the cheat would only affect multiple addresses if/when they actually do mirror one another. It's not as simple as just ignoring the highest bit of the address, etc.

**Comment by undisbeliever** [comment]
>No it won't; just like with single breakpoints, the cheat would only affect multiple addresses if/when they actually do mirror one another

Oh, that's good to know. I withdraw my objection then.
